#ifndef EXAMPLE_H
#define EXAMPLE_H

const char *example[] =
		"LLLLLLLLLLLLLLLLLLLLLWLLLWLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWWLLWLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWLWLWLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWLLWWLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWLLLWLLLLLLLLLLLLLLLLLLLL"
		"LLLLL                                    LLLLL"
		"WLLLW 0123 !@# k .:; b   T J _a  /   W m WWWWW"
		"WLLLW  456 $%^ x efs r X     il /W/      WLLLL"
		"WLWLW  789 &*    hHM n        d L/L  g ~ WWWWL"
		"WWLWW  ABC       +IQ          D LLL      WLLLL"
		"WLLLW            R       t j    LLL      WWWWW"
		"LLLLL                           LLL      LLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWWWWWLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWWWWWLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLL"
		"LLLLLLLLLLLLLLLLLLLLLWWWWWLLLLLLLLLLLLLLLLLLLL";

#endif // EXAMPLE_H
