language: cpp

# OS config, depends on actual 'os' in build matrix
dist: xenial

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache/$TRAVIS_BRANCH
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="debug_symbols=no verbose=yes progress=no"

cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - name: iOS export template (release, Clang)
      stage: build
      env: PLATFORM=iphone TOOLS=no TARGET=release CACHE_NAME=${PLATFORM}-clang
      os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
            - scons
          update: true

before_install:
  - eval "${MATRIX_EVAL}"
  - scons --version

script:
  - scons -j2 CC=$CC CXX=$CXX platform=$PLATFORM tools=$TOOLS target=$TARGET $OPTIONS $EXTRA_ARGS
