#!/usr/bin/env python

Import("env")

if "METAL_SL" in env["BUILDERS"]:
    env.METAL_SL("copy.metal")
    env.METAL_SL("resolve.metal")
    env.METAL_SL("canvas.metal")
    env.METAL_SL("canvas_shadow.metal")
    env.METAL_SL("scene.metal")
    env.METAL_SL("cubemap_filter.metal")
    env.METAL_SL("cube_to_dp.metal")
    env.METAL_SL("blend_shape.metal")
    env.METAL_SL("screen_space_reflection.metal")
    env.METAL_SL("effect_blur.metal")
    env.METAL_SL("subsurf_scattering.metal")
    env.METAL_SL("ssao.metal")
    env.METAL_SL("ssao_minify.metal")
    env.METAL_SL("ssao_blur.metal")
    env.METAL_SL("exposure.metal")
    env.METAL_SL("tonemap.metal")
    env.METAL_SL("particles.metal")
    env.METAL_SL("lens_distorted.metal")
