#!/usr/bin/env python3
"""
bake_material_symbols.py — pre-rasterise the manifest's icons.

Drives the editor binary (which has the full MaterialSymbols class with
FreeType and the variable-axis renderer) via `--no-window --script` to
produce one PNG per manifest entry, then embeds them all as inline byte
arrays in `material_symbols_baked.gen.cpp` along with a sorted
(name, tag) lookup table.

Usage:
    bake_material_symbols.py \\
        --manifest /path/to/material_symbols.subset \\
        --editor   /path/to/godot.osx.opt.tools.arm64 \\
        --out-cpp  submodules/material_symbols/material_symbols_baked.gen.cpp

Manifest format (lines, # comments, blanks ignored):
    name [tag=t] [style=outlined|rounded|sharp] [size=N] \\
                 [weight=N] [grade=N] [opsz=N] [fill=F] [color=RRGGBB]
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

VALID_STYLES = ("outlined", "rounded", "sharp")
DEFAULTS = {
    "tag": "default",
    "style": "rounded",
    "size": "24",
    "weight": "400",
    "grade": "0",
    "opsz": "24",
    "fill": "0",
    "color": "ffffff",
}


def parse_manifest(path: Path):
    records = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        tokens = line.split()
        name = tokens[0]
        opts = dict(DEFAULTS)
        for tok in tokens[1:]:
            if "=" not in tok:
                print(f"bake_material_symbols: ignoring stray token '{tok}' in line: {raw}", file=sys.stderr)
                continue
            k, v = tok.split("=", 1)
            if k not in DEFAULTS:
                print(f"bake_material_symbols: unknown key '{k}' in line: {raw}", file=sys.stderr)
                continue
            opts[k] = v
        if opts["style"] not in VALID_STYLES:
            print(f"bake_material_symbols: bad style '{opts['style']}' (line: {raw})", file=sys.stderr)
            continue
        records.append((name, opts))
    return records


def hex_to_floats(hex_color: str):
    h = hex_color.lstrip("#")
    if len(h) != 6:
        return (1.0, 1.0, 1.0)
    return (int(h[0:2], 16) / 255.0, int(h[2:4], 16) / 255.0, int(h[4:6], 16) / 255.0)


def make_runner_script(records, out_dir: Path):
    """Generate a SceneTree-init script that renders each record."""
    lines = [
        "extends SceneTree",
        "",
        "func _init():",
        "    var ms = MaterialSymbols.new()",
        '    print("[bake] %d records" % %d)' % (len(records), 0) if False else f'    print("[bake] {len(records)} records")',
    ]
    # Strip the failed conditional from above; just emit directly.
    lines = [
        "extends SceneTree",
        "",
        "func _init():",
        "    var ms = MaterialSymbols.new()",
        f'    print("[bake] {len(records)} records")',
    ]
    for i, (name, opts) in enumerate(records):
        style_const = "MaterialSymbols.STYLE_" + opts["style"].upper()
        size = int(opts["size"])
        weight = int(opts["weight"])
        grade = int(opts["grade"])
        opsz = int(opts["opsz"])
        fill = float(opts["fill"])
        r, g, b = hex_to_floats(opts["color"])
        png_path = str(out_dir / f"{i:04d}.png")
        lines += [
            "    var img_%d = ms.get_image(%s, \"%s\", %d, {"
            "\"color\": Color(%g, %g, %g), \"weight\": %d, \"grade\": %d, "
            "\"opsz\": %d, \"fill\": %g})"
            % (i, style_const, name, size, r, g, b, weight, grade, opsz, fill),
            "    if img_%d:" % i,
            "        img_%d.save_png(\"%s\")" % (i, png_path),
            "    else:",
            "        push_warning(\"[bake] missing: %s @ %s\")" % (name, opts["style"]),
        ]
    lines += ["    quit()", ""]
    return "\n".join(lines)


def emit_cpp(records, png_files, out_cpp: Path):
    """Emit material_symbols_baked.gen.cpp with sorted (name, tag) entries
    and inline PNG byte arrays."""
    # Sort by (name, tag) for binary search at runtime.
    bundles = []
    missing = 0
    for (name, opts), png in zip(records, png_files):
        if png is None or not png.exists() or png.stat().st_size == 0:
            missing += 1
            continue
        bundles.append((name, opts["tag"], png.read_bytes()))
    bundles.sort(key=lambda b: (b[0], b[1]))

    lines = [
        "// AUTOGENERATED by bake_material_symbols.py — do not edit by hand.",
        '#include "material_symbols_baked.gen.h"',
        "",
        "namespace material_symbols_baked {",
        "",
    ]
    for i, (_n, _t, blob) in enumerate(bundles):
        lines.append(f"static const unsigned char png_{i}[{len(blob)}] = {{")
        chunks = []
        for k in range(0, len(blob), 16):
            chunks.append("    " + ", ".join(f"0x{b:02x}" for b in blob[k:k + 16]))
        lines.append(",\n".join(chunks))
        lines.append("};")
    lines.append("")
    lines.append(f"const Entry entries[{len(bundles)}] = {{")
    for i, (n, t, blob) in enumerate(bundles):
        ne = n.replace("\\", "\\\\").replace('"', '\\"')
        te = t.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {{ "{ne}", "{te}", png_{i}, {len(blob)} }},')
    lines.append("};")
    lines.append(f"const int entries_count = {len(bundles)};")
    lines.append("")
    lines.append("} // namespace material_symbols_baked")
    lines.append("")

    out_cpp.parent.mkdir(parents=True, exist_ok=True)
    out_cpp.write_text("\n".join(lines), encoding="utf-8")
    return missing


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", type=Path, required=True)
    ap.add_argument("--editor", type=Path, required=True)
    ap.add_argument("--out-cpp", type=Path, required=True)
    args = ap.parse_args()

    if not args.manifest.is_file():
        sys.exit(f"manifest not found: {args.manifest}")
    if not args.editor.is_file() or not os.access(args.editor, os.X_OK):
        sys.exit(f"editor binary not found or not executable: {args.editor}")

    records = parse_manifest(args.manifest)
    if not records:
        print("(bake) manifest is empty — emitting an empty baked table.")
        emit_cpp([], [], args.out_cpp)
        return

    print(f"(bake) {len(records)} records from {args.manifest}")

    with tempfile.TemporaryDirectory(prefix="ms_bake_") as tmp:
        tmp_dir = Path(tmp)
        runner = tmp_dir / "bake_runner.gd"
        runner.write_text(make_runner_script(records, tmp_dir), encoding="utf-8")
        cmd = [str(args.editor), "--no-window", "--script", str(runner)]
        print("(bake) running:", " ".join(cmd))
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            print(res.stdout, file=sys.stderr)
            print(res.stderr, file=sys.stderr)
            sys.exit(f"(bake) editor exited {res.returncode}")
        png_files = [tmp_dir / f"{i:04d}.png" for i in range(len(records))]
        missing = emit_cpp(records, png_files, args.out_cpp)
        if missing:
            print(f"(bake) WARN: {missing} record(s) failed to render — see editor stderr above.")
        baked = len(records) - missing
        print(f"(bake) baked {baked} icons into {args.out_cpp}")


if __name__ == "__main__":
    main()
