#!/usr/bin/env python3
"""
gen_material_symbols_data.py — codegen for the Material Symbols submodule.

Reads the three .codepoints files (one per style) and emits sorted-by-name
(name, codepoint) tables. The TTF binaries are NOT embedded by this script
— they are pulled in at link time by `material_symbols_resources.c` via
INCBIN, which keeps the .cpp tiny and the build fast.

Output: material_symbols_data.gen.{h,cpp}
"""

import argparse
import sys
from pathlib import Path

STYLES = [
    ("Outlined", "outlined"),
    ("Rounded", "rounded"),
    ("Sharp", "sharp"),
]


def read_codepoints(path: Path):
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) != 2:
            continue
        name, hex_cp = parts
        try:
            cp = int(hex_cp, 16)
        except ValueError:
            continue
        out.append((name, cp))
    out.sort(key=lambda x: x[0])
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=Path, required=True, help="thirdparty/material_symbols root")
    ap.add_argument("--out-h", type=Path, required=True)
    ap.add_argument("--out-cpp", type=Path, required=True)
    args = ap.parse_args()
    if not args.src.is_dir():
        sys.exit(f"no such dir: {args.src}")

    args.out_h.parent.mkdir(parents=True, exist_ok=True)
    args.out_cpp.parent.mkdir(parents=True, exist_ok=True)

    h = [
        "// AUTOGENERATED by gen_material_symbols_data.py — do not edit by hand.",
        "#ifndef MATERIAL_SYMBOLS_DATA_GEN_H",
        "#define MATERIAL_SYMBOLS_DATA_GEN_H",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace material_symbols_data {",
        "",
        "struct Entry {",
        "    const char *name;",
        "    uint32_t codepoint;",
        "};",
        "",
    ]
    cpp = [
        "// AUTOGENERATED by gen_material_symbols_data.py — do not edit by hand.",
        '#include "material_symbols_data.gen.h"',
        "",
        "namespace material_symbols_data {",
        "",
    ]

    for pretty, slug in STYLES:
        cp_path = args.src / "codepoints" / f"{pretty}.codepoints"
        if not cp_path.is_file():
            sys.exit(f"missing {cp_path}")

        entries = read_codepoints(cp_path)
        h.append(f"extern const Entry entries_{slug}[{len(entries)}];")
        h.append(f"constexpr int entries_{slug}_count = {len(entries)};")
        h.append("")

        cpp.append(f"const Entry entries_{slug}[{len(entries)}] = {{")
        for name, cp in entries:
            esc = name.replace("\\", "\\\\").replace('"', '\\"')
            cpp.append(f'    {{ "{esc}", 0x{cp:x}u }},')
        cpp.append("};")
        cpp.append("")

        print(f"  {pretty}: {len(entries)} entries")

    h += [
        "} // namespace material_symbols_data",
        "",
        "// TTFs are embedded via INCBIN in material_symbols_resources.c — these",
        "// declarations live at global scope to match INCBIN's emitted symbols.",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "extern const unsigned char ttf_outlined_data[];",
        "extern const unsigned int ttf_outlined_size;",
        "extern const unsigned char ttf_rounded_data[];",
        "extern const unsigned int ttf_rounded_size;",
        "extern const unsigned char ttf_sharp_data[];",
        "extern const unsigned int ttf_sharp_size;",
        "#ifdef __cplusplus",
        '} // extern "C"',
        "#endif",
        "",
        "#endif // MATERIAL_SYMBOLS_DATA_GEN_H",
        "",
    ]
    cpp += ["} // namespace material_symbols_data", ""]

    args.out_h.write_text("\n".join(h), encoding="utf-8")
    args.out_cpp.write_text("\n".join(cpp), encoding="utf-8")


if __name__ == "__main__":
    main()
