#!/usr/bin/env python
import os

Import("env")
Import("env_modules")

env_modules.add_source_files(env.modules_sources, "*.cpp")
env_modules.add_source_files(env.modules_sources, "gd/*.cpp")
env_modules.add_source_files(env.modules_sources, "gd/*.c")
env_modules.add_source_files(env.modules_sources, "gd2c/*.cpp")
env_modules.add_source_files(env.modules_sources, "scene/*.cpp")
env_modules.add_source_files(env.modules_sources, "statemachine/*.cpp")
env_modules.add_source_files(env.modules_sources, "debugdraw/*.cpp")
env_modules.add_source_files(env.modules_sources, "benet/*.cpp")
env_modules.add_source_files(env.modules_sources, "behaviornode/*.cpp")

env_modules.Append(CPPPATH=["#thirdparty/enet/", os.path.dirname(os.path.realpath(os.curdir)) + "/gdnative/include"])
env_modules.Append(CPPFLAGS=["-DGD_GODOT_ENET"])
