#!/usr/bin/env python
import os

Import("env")
Import("env_modules")

env_module = env_modules.Clone()

sources = Glob("*.cpp")
modules = ["gd", "gd2c", "scene", "scenery/tree_2d", "scenery/spherical_waves", "scenery/water_splash", "scenery/vegetation_instance", "debugdraw", "statemachine", "benet", "behaviornode"]
for m in modules:
    sources += Glob("%s/*.cpp"%m)
    sources += Glob("%s/*.c"%m)

env_module.Append(CPPPATH=["#thirdparty/enet/", os.path.dirname(os.path.realpath(os.curdir)) + "/gdnative/include"])
env_module.Append(CPPFLAGS=["-DGD_GODOT_ENET"])

# Compile as a static library
lib = env_module.Library("gd_custom_extensions", sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
