/* DO NOT EDIT!  This file is generated by gdgenblit.pl */

#include "_internal.h"

#if SDL_HAVE_BLIT_AUTO

extern SDL_BlitFuncEntry SDL_GeneratedBlitFuncTable[];

#endif /* SDL_HAVE_BLIT_AUTO */

/* vi: set ts=4 sw=4 expandtab: */
