#!/usr/bin/env python3
"""Draw the sparkline glyph family into PBM sheets shaped like the fonts.altered atlases.

Usage: make_sparkline.py [-i INPUT_DIR] [-o OUTPUT_DIR] [-c FIRST_CODE] [-n STEPS]

A sparkline column is a cell filled from the baseline up to a fraction of its height, the
CP437 equivalent of U+2581..U+2587. The console already has the two ends of the family --
0x20 (empty) and 0xdb (full block) -- so only the intermediate levels are generated.

Every sheet is the exact size of its atlas and carries the new glyphs at their cell
positions in the *drawn* (visual bottom) half, so it can be opened over the .xcf, aligned
at (0, 0), and merged cell by cell. The reversed top half is left black and must stay
untouched: make_fonts.py recovers the CP437 glyph itself from there.

Destination codes and the shape of every glyph are written to make_sparkline.log.
"""

import argparse
import os
import sys

import glyphsheet as gs

FAMILY = "sparkline"


def sparkline_glyph(char_w, char_h, lit_rows):
    """A full-width block `lit_rows` tall, anchored to the baseline."""
    return [[1 if y >= char_h - lit_rows else 0 for _ in range(char_w)] for y in range(char_h)]


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-i", "--input", default=gs.DEFAULT_INPUT, help="folder of atlases (default fonts.altered/)")
    parser.add_argument("-o", "--output", default=gs.DEFAULT_OUTPUT, help="where the sheets are written")
    parser.add_argument("-c", "--first-code", default="0x80", help="first destination code (default 0x80)")
    parser.add_argument("-n", "--steps", type=int, default=7, help="intermediate levels (default 7)")
    parser.add_argument("-l", "--log", default=os.path.join(gs.HERE, "make_sparkline.log"))
    args = parser.parse_args()

    first_code = int(args.first_code, 0)
    codes = list(range(first_code, first_code + args.steps))
    log = gs.Log()

    faces = gs.discover_faces(args.input)
    if not faces:
        sys.stderr.write("no atlases in %s\n" % args.input)
        return 1
    if codes[-1] > 0xFF:
        sys.stderr.write("0x%02x + %d steps runs past the end of the atlas\n" % (first_code, args.steps))
        return 1

    log("sparkline glyphs: %d levels of %d, filled from the baseline up" % (args.steps, args.steps + 1))
    log("")
    log("destination codes")
    log("-----------------")
    log("These are bank 1 (drawn half) patches. The CP437 glyph each one displaces is only")
    log("displaced when a string asks for that code in bank 1, i.e. through the \\x01 toggle;")
    log("plain text at the same code still draws the letter from bank 0.")
    log("")
    for i, code in enumerate(codes):
        log(
            "  0x%02x  level %d/%d  (currently the reverse of CP437 %s)"
            % (code, i + 1, args.steps + 1, gs.cp437_name(code))
        )
    log("")
    codes_ok = gs.check_codes(codes, log)

    os.makedirs(args.output, exist_ok=True)
    duplicates = []
    for name, path, char_w, char_h in faces:
        extents = gs.levels(args.steps, char_h)
        sheet = gs.Sheet(char_w, char_h)
        entries = []
        for code, lit in zip(codes, extents):
            bitmap = sparkline_glyph(char_w, char_h, lit)
            sheet.blit(code, bitmap)
            entries.append(("0x%02x" % code, gs.ascii_art(bitmap)))

        atlas_w, atlas_h = gs.atlas_size(path)
        if (atlas_w, atlas_h) != (sheet.width, sheet.height):
            log(
                "NOTICE: %s is %dx%d but a %s atlas should be %dx%d"
                % (os.path.basename(path), atlas_w, atlas_h, name, sheet.width, sheet.height)
            )
            codes_ok = False

        out = os.path.join(args.output, "%s_%s.pbm" % (name, FAMILY))
        sheet.write_pbm(
            out,
            [
                "%s glyphs for the %s face, generated by make_sparkline.py" % (FAMILY, name),
                "merge into the drawn (lower) half of %s only" % os.path.basename(path),
                "codes %s" % " ".join("0x%02x" % c for c in codes),
                "lit pixels are white: paste into the drawn (lower) half of the atlas as-is",
            ],
        )

        log(
            "%-5s %2dx%-2d  rows %-22s  %s"
            % (name, char_w, char_h, ",".join(str(e) for e in extents), os.path.relpath(out, gs.HERE))
        )
        if len(set(extents)) != len(extents):
            duplicates.append(name)
        log.quiet("")
        for line in gs.art_columns(entries):
            log.quiet("  " + line)
        log.quiet("")

    log("")
    for name in duplicates:
        log("NOTICE: %s is too short to resolve %d distinct levels; some codes repeat a shape" % (name, args.steps))
    log("wrote %d sheets to %s" % (len(faces), os.path.relpath(args.output, gs.HERE)))
    log.write(args.log, sys.argv)
    return 0 if codes_ok else 1


if __name__ == "__main__":
    sys.exit(main())
