#!/usr/bin/env python

Import('env')
Import('env_modules')

env_module = env_modules.Clone()
env_module.Append(CPPPATH=[".", "include"])

env_module.add_source_files(env.modules_sources, "*.cpp")
env_module.add_source_files(env.modules_sources, "src/*.cpp")

sources = Glob("*.cpp")
sources += Glob("src/*.cpp")

# Compile as a static library
lib = env_module.Library("gd_generator", sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
