#!/usr/bin/env python3

Import("env")
Import("env_goost")

if env["goost_image_enabled"]:
    SConscript("image/SCsub", exports="env_goost")

if env["goost_math_enabled"]:
    SConscript("math/SCsub", exports="env_goost")

if env["goost_script_enabled"]:
    SConscript("script/SCsub", exports="env_goost")

env_goost.add_source_files(env_goost.sources, "*.cpp")
env_goost.add_source_files(env_goost.sources, "types/*.cpp")

if env["tools"]:
    env_goost.add_source_files(env_goost.sources, "types/editor/*.cpp")
