#!/usr/bin/env python

Import("env")

env.drivers_sources = []

# OS drivers
SConscript("unix/SCsub")
SConscript("windows/SCsub")

# Sounds drivers
SConscript("alsa/SCsub")
SConscript("coreaudio/SCsub")
SConscript("pulseaudio/SCsub")
if env["platform"] == "windows":
    SConscript("wasapi/SCsub")
if env["xaudio2"]:
    SConscript("xaudio2/SCsub")

# Midi drivers
SConscript("alsamidi/SCsub")
SConscript("coremidi/SCsub")
SConscript("winmidi/SCsub")
SConscript("fluidsynth/SCsub")

# Graphics drivers
if env["platform"] != "3ds" and env["platform"] != "psp":
    if env["platform"] != "server":
        if not env["disable_3d"] and env["platform"] != "psvita":
            SConscript("gles3/SCsub")
        SConscript("gles2/SCsub")
        SConscript("gles_common/SCsub")
        SConscript("gl_context/SCsub")
        if env["platform"] == "osx" or env["platform"] == "iphone":
            SConscript("gles3+mgl/SCsub")
    else:
        SConscript("dummy/SCsub")

# Core dependencies
SConscript("png/SCsub")

env.add_source_files(env.drivers_sources, "*.cpp")

lib = env.add_library("drivers", env.drivers_sources)
env.Prepend(LIBS=[lib])
