#!/usr/bin/env python

Import('env')
Import('env_modules')

env_generator = env_modules.Clone()

# Integration source files
sources = Glob("*.cpp")
# Library source files
sources += [
    "src/bulletmlparser-tinyxml.cpp",
    "src/bulletmlparser.cpp",
    "src/bulletmltree.cpp",
    "src/calc.cpp",
    "src/formula-variables.cpp",
    "src/bulletmlrunner.cpp",
    "src/bulletmlrunnerimpl.cpp",
    "src/tinyxml/tinyxml.cpp",
    "src/tinyxml/tinyxmlerror.cpp",
    "src/tinyxml/tinyxmlparser.cpp"
]

# Generator include path
env_generator.Append(CPPPATH=[".", "include"])

# Compilation flags
env_generator.Append(CXXFLAGS=['-std=c++11'])

# Compile as a static library
lib = env_generator.Library("bullet_hell", sources)

# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
