#!/usr/bin/env python

Import("env")
Import("env_modules")

SConscript("editor/icons/SCsub")

env_gdsdecomp = env_modules.Clone()

env_gdsdecomp.Append(CPPPATH=["."])
env_gdsdecomp.Append(CPPPATH=["#thirdparty/nanosvg/"])

sources = Glob("*.cpp") + Glob("bytecode/*.cpp") + Glob("editor/*.cpp")

# Compile as a static library
lib = env_gdsdecomp.Library("gdsdecomp", sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
