#!/usr/bin/env python3

Import("env")
Import("env_goost")

env_goost.add_source_files(env_goost.sources, "*.cpp")
env_goost.add_source_files(env_goost.sources, "mixin_script/*.cpp")

if env["tools"]:
    env_goost.add_source_files(env_goost.sources, "mixin_script/editor/*.cpp")
