/**************************************************************************/
/*  debug_console.cpp                                                     */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#include "debug_console.h"
#include "console_gauge.h"
#include "console_lcd.h"
#include "console_raster.h"
#include "figlet_font.h"

#include "core/os/secondary_display.h"

#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sstream>
#include <string>
#include <vector>

#include "core/os/dir_access.h"
#include "core/os/file_access.h"
#include "core/os/os.h"
#include "core/version.h"
#include "main/performance.h"
#include "servers/visual_server.h"

#if defined(UNIX_ENABLED) && !defined(NO_STATVFS)
#include <sys/statvfs.h>
#endif
#if defined(__linux__) || defined(ANDROID_ENABLED)
#include <dirent.h>
#endif
#include "scene/resources/mesh.h"
#include "scene/resources/texture.h"

#ifdef DOCTEST
#include "doctest/doctest.h"
#else
#define DOCTEST_CONFIG_DISABLE
#endif

#ifndef BIND_ENUM_CONSTANT_CUSTOM
#define BIND_ENUM_CONSTANT_CUSTOM(pConstant, pName) \
	ClassDB::bind_integer_constant(get_class_static(), StringName(), pName, ((int)(pConstant)));
#endif
#define newref(pClass) Ref<pClass>(memnew(pClass))
#define _register_global_ref(pRef)                        \
	{                                                     \
		if (SceneTree *sc = SceneTree::get_singleton()) { \
			sc->add_exit_callback([=]() {                 \
				pRef.unref();                             \
			});                                           \
		}                                                 \
	}

#ifdef DEBUG_ENABLED
#define DEBUG_PRINT(m_text) print_line(m_text);
#else
#define DEBUG_PRINT(m_text)
#endif

typedef struct {
	const char *image;
	const unsigned char *pixels;
	int char_w, char_h, size, width, height, channels;
	const unsigned char *patch; // bank 1 glyph blocks, char_w * char_h bytes each
	const unsigned char *patch_codes; // the code each block belongs to
	int patch_count;
} EmbedImageItem;

#define FORMAT_1CHANNEL 1
#define FORMAT_3CHANNEL 3
#define FORMAT_4CHANNEL 4

#include "dos_font_data.h"

// Bank 0 is the 256 unaltered CP437 glyphs. The atlas texture is allocated at twice this
// height; the lower half is bank 1, which only holds the patched glyphs below -- every other
// bank 1 code falls back to inverting the bank 0 glyph at draw time.
// Regenerated by modules/gdextensions/_tools/make_fonts.py. See CONSOLE.md section 7.
constexpr EmbedImageItem embed_debug_font[] = {
	{ "dos-8x16", font_8x16, 8, 16, 98304 / 3, 128, 256, FORMAT_1CHANNEL, font_8x16_patch, font_8x16_patch_codes, FONT_8X16_PATCH_COUNT },
	{ "dos-8x12", font_8x12, 8, 12, 73728 / 3, 128, 192, FORMAT_1CHANNEL, font_8x12_patch, font_8x12_patch_codes, FONT_8X12_PATCH_COUNT },
	{ "dos-8x8", font_8x8, 8, 8, 49152 / 3, 128, 128, FORMAT_1CHANNEL, font_8x8_patch, font_8x8_patch_codes, FONT_8X8_PATCH_COUNT },
	{ "dos-7x9", font_7x9, 7, 9, 48384 / 3, 112, 144, FORMAT_1CHANNEL, font_7x9_patch, font_7x9_patch_codes, FONT_7X9_PATCH_COUNT },
	{ "dos-4x6", font_4x6, 4, 6, 18432 / 3, 64, 96, FORMAT_1CHANNEL, font_4x6_patch, font_4x6_patch_codes, FONT_4X6_PATCH_COUNT },
	{ NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, 0 }
};

namespace Figlet {
constexpr Banner *fig_font_mapping[] = {
	&future,
	&calvins,
	&ansiregular,
	&ansishadow,
	&dosrebel,
	&maxiwi,
	&miniwi,
	&maxii,
};
}

static PoolByteArray _poolbytearray_from_data(const uint8_t *bytes, size_t bytes_size, int bytes_channels, Image::Format dest_format) {
	PoolByteArray data;
	if (bytes_channels == FORMAT_1CHANNEL && dest_format == Image::Format::FORMAT_LA8) {
		data.resize(2 * bytes_size);
		PoolByteArray::Write wr = data.write();
		for (size_t b = 0; b < 2 * bytes_size; b += 2) {
			wr[b] = wr[b + 1] = bytes[b >> 1];
		}
	} else if (bytes_channels == FORMAT_1CHANNEL && dest_format == Image::Format::FORMAT_RGB8) {
		data.resize(3 * bytes_size);
		PoolByteArray::Write wr = data.write();
		for (size_t b = 0; b < 3 * bytes_size; b += 3) {
			wr[b] = wr[b + 1] = wr[b + 3] = bytes[b / 3];
		}
	} else if (bytes_channels == FORMAT_1CHANNEL && dest_format == Image::Format::FORMAT_RGBA8) {
		data.resize(4 * bytes_size);
		PoolByteArray::Write wr = data.write();
		for (size_t b = 0; b < 4 * bytes_size; b += 4) {
			wr[b] = wr[b + 1] = wr[b + 3] = wr[b + 4] = bytes[b >> 2];
		}
	} else {
		data.resize(bytes_size);
		memcpy(data.write().ptr(), bytes, bytes_size);
	}
	return data;
}

static Ref<Texture> _font_cache[TextConsole::DosFontCount];

static Image::Format _atlas_format(int p_channels) {
	constexpr Image::Format formats[] = {
		Image::Format::FORMAT_MAX,
		Image::Format::FORMAT_LA8,
		Image::Format::FORMAT_LA8,
		Image::Format::FORMAT_RGBA8,
		Image::Format::FORMAT_RGBA8,
	};
	return formats[p_channels];
}

void TextConsole::cleanup_font_cache() {
	for (int i = 0; i < DosFontCount; ++i) {
		_font_cache[i].unref();
	}
}

void TextConsole::load_font(FontSize p_font) {
	ERR_FAIL_INDEX(p_font, DosFontCount);

	const EmbedImageItem &data = embed_debug_font[p_font];

	if (!_font_cache[p_font].is_valid()) {
		const Image::Format format = _atlas_format(data.channels);

		// The embedded data only holds the 256 bank 0 glyphs. Allocate a texture of
		// BANK_COUNT times that height: bank 1 carries the patched glyphs at their own code
		// index (every other bank 1 code stays blank and is rendered by inverting the bank 0
		// glyph in _update_mesh()), and bank 2 is left blank for the runtime generators.
		PoolByteArray pixels = _poolbytearray_from_data(data.pixels, data.size, data.channels, format);
		const int static_size = pixels.size();
		const int channels = pixels.size() / data.size;
		pixels.resize(static_size * BANK_COUNT);
		{
			PoolByteArray::Write wr = pixels.write();
			memset(wr.ptr() + static_size, 0, static_size * (BANK_COUNT - 1));

			for (int i = 0; i < data.patch_count; ++i) {
				const int code = data.patch_codes[i];
				const int gx = (code % 16) * data.char_w;
				const int gy = (code / 16) * data.char_h;
				const uint8_t *src = data.patch + i * data.char_w * data.char_h;
				for (int y = 0; y < data.char_h; ++y) {
					uint8_t *dst = wr.ptr() + static_size + ((gy + y) * data.width + gx) * channels;
					for (int x = 0; x < data.char_w; ++x) {
						for (int c = 0; c < channels; ++c) {
							dst[x * channels + c] = src[y * data.char_w + x];
						}
					}
				}
			}
		}

		Ref<Image> image = newref(Image);
		image->create(data.width, data.height * BANK_COUNT, false, format, pixels);
		Ref<ImageTexture> font_texture = newref(ImageTexture);
		font_texture->create_from_image(image, 0);
		_font_cache[p_font] = font_texture;

		_register_global_ref(_font_cache[p_font]);
	}

	_font_face = p_font;
	_font_size = Size2i(data.char_w, data.char_h);

	// Which codes actually have a bank 1 glyph; the rest fall back to inversion.
	memset(_has_patch, 0, sizeof(_has_patch));
	for (int i = 0; i < data.patch_count; ++i) {
		_has_patch[data.patch_codes[i]] = true;
	}

	// 16 columns across, 16 rows per bank, BANK_COUNT banks stacked vertically.
	const real_t du = 1.0 / 16.0;
	const real_t dv = 1.0 / (16.0 * BANK_COUNT);
	for (int ch = 0; ch < 256 * BANK_COUNT; ++ch) {
		const real_t cx = (ch % 16) * du;
		const real_t cy = (ch / 16) * dv;

		_chars[ch].t[0] = Point2(cx, cy); /* 0, 0 */
		_chars[ch].t[1] = Point2(cx, cy + dv); /* 0, 1 */
		_chars[ch].t[2] = Point2(cx + du, cy); /* 1, 0 */
		_chars[ch].t[3] = Point2(cx + du, cy + dv); /* 1, 1 */
	}
}

void TextConsole::clear() {
	ERR_FAIL_COND(_screen == 0);
	memset(_screen, 0, sizeof(cell) * _con_size.width * _con_size.height);
	_cursor_pos = Point2i(0, 0);
	_dirty_screen = true;
}

// The startup box. Returned as plain lines rather than printed directly so ConsoleInstance
// can seed its log ring buffer with them: the grid is rebuilt from that buffer on every
// reflow, and anything written straight to the cells would be lost.
void console_banner_lines(Vector<String> &r_text, Vector<int> &r_color) {
	r_text.push_back(String(BOX_DDR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DDL));
	r_color.push_back(TextConsole::COLOR_LIGHTGRAY);
	r_text.push_back(String(BOX_DUD "   \x01Godot Engine\x01 debug console   " BOX_DUD));
	r_color.push_back(TextConsole::COLOR_LIGHTGRAY);
	r_text.push_back(String(BOX_DUD "    \xfeKomSoft Oprogramowanie\xfe    " BOX_DUD));
	r_color.push_back(TextConsole::COLOR_LIGHTGRAY);
	r_text.push_back(String(BOX_DUR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DLR BOX_DUL));
	r_color.push_back(TextConsole::COLOR_LIGHTGRAY);
	r_text.push_back(String("\020 " VERSION_FULL_NAME));
	r_color.push_back(TextConsole::COLOR_DEFAULT);
	r_text.push_back(vformat("\020 %s", OS::get_singleton()->get_video_driver_name(OS::get_singleton()->get_current_video_driver())));
	r_color.push_back(TextConsole::COLOR_DEFAULT);
	r_text.push_back(String("\020 \x01Ready..\x01"));
	r_color.push_back(TextConsole::COLOR_GREEN);
}

void TextConsole::print_banner() {
	Vector<String> text;
	Vector<int> color;
	console_banner_lines(text, color);
	for (int i = 0; i < text.size(); ++i) {
		logl(text[i], ColorIndex(color[i]));
	}
}

bool TextConsole::resize(const Viewport *p_view) {
	ERR_FAIL_COND_V(p_view == nullptr, false);

	const Size2i size = p_view->get_visible_rect().size;
	const Size2i cell = get_cell_size();
	ERR_FAIL_COND_V(cell.width < 1 || cell.height < 1, false);
	// console size, in whole cells
	return resize(MAX(1, size.width / cell.width), MAX(1, size.height / cell.height));
}

bool TextConsole::resize(int p_cols, int p_rows) {
	ERR_FAIL_COND_V(p_cols < 1, false);
	ERR_FAIL_COND_V(p_rows < 1, false);

	_con_size.width = p_cols;
	_con_size.height = p_rows;

	if (_screen)
		memdelete_arr(_screen);
	_screen = memnew_arr(cell, _con_size.width * _con_size.height);
	memset(_screen, 0, sizeof(cell) * _con_size.width * _con_size.height);
	_cursor_pos = Point2i(0, 0);

	DEBUG_PRINT(vformat("New console resized: %dx%d", p_cols, p_rows));

	return true;
}

static Color palette[TextConsole::COLOR_COUNT] = {
	/*  0. BLACK        */ Color::from_abgr(0xFF000000),
	/*  1. BLUE         */ Color::from_abgr(0xFFFF0000),
	/*  2. GREEN        */ Color::from_abgr(0xFF00FF00),
	/*  3. CYAN         */ Color::from_abgr(0xFFFFFF00),
	/*  4. RED          */ Color::from_abgr(0xFF0000FF),
	/*  5. MAGENTA      */ Color::from_abgr(0xFFFF00FF),
	/*  6. BROWN        */ Color::from_abgr(0xFF2A2AA5),
	/*  7. LIGHTGRAY    */ Color::from_abgr(0xFFD3D3D3),
	/*  8. DARKGRAY     */ Color::from_abgr(0xFFA9A9A9),
	/*  9. LIGHTBLUE    */ Color::from_abgr(0xFFE6D8AD),
	/* 10. LIGHTGREEN   */ Color::from_abgr(0xFF90EE90),
	/* 11. LIGHTCYAN    */ Color::from_abgr(0xFFFFFFE0),
	/* 12. LIGHTRED     */ Color::from_abgr(0xFFCBCCFF),
	/* 13. LIGHTMAGENTA */ Color::from_abgr(0xFFF942FF),
	/* 14. YELLOW       */ Color::from_abgr(0xFF0FFEFF),
	/* 15. WHITE        */ Color::from_abgr(0xFFFFFFFF),
	/* 16. TRANSPARENT  */ Color::from_abgr(0x00000000),
};

// Exposed for the software rasterizer (console_raster.cpp), which cannot see the tables
// above but must agree with them exactly.
const Color *console_get_palette() {
	return palette;
}

ConsoleFontSource console_get_font_source(TextConsole::FontSize p_font) {
	ConsoleFontSource src = { nullptr, nullptr, nullptr, 0, 0, 0, 0 };
	ERR_FAIL_INDEX_V(p_font, TextConsole::DosFontCount, src);

	const EmbedImageItem &data = embed_debug_font[p_font];
	src.pixels = data.pixels;
	src.patch = data.patch;
	src.patch_codes = data.patch_codes;
	src.patch_count = data.patch_count;
	src.char_w = data.char_w;
	src.char_h = data.char_h;
	src.atlas_w = data.width;
	return src;
}

Point2i TextConsole::_write(const String &p_msg, Point2i pos, ColorIndex foreground, ColorIndex background) {
	ERR_FAIL_COND_V(_screen == 0, pos);
	ERR_FAIL_COND_V(pos.x >= _con_size.width, pos);
	ERR_FAIL_COND_V(pos.y >= _con_size.height, pos);

	// Resolve COLOR_DEFAULT here: it is a sentinel, not a palette entry, and inverting a
	// cell swaps the background into the foreground where it would index palette[] out of
	// bounds.
	if (foreground == COLOR_DEFAULT) {
		foreground = _default_fg_color_index;
	}
	if (background == COLOR_DEFAULT) {
		background = _default_bg_color_index;
	}

	// \x01 toggles the glyph bank for the characters that follow, except that \x01\x01 is
	// not a toggle of a toggle: it draws code 1 of bank 1, which is what keeps that code
	// usable as a glyph slot of its own. Bank 1 holds the patched glyphs, and any code
	// without one is rendered as the inverted bank 0 glyph, see _update_mesh().
	uint8_t bank = BANK_CP437;
	const CharString ascii = p_msg.ascii();
	// length(), not size(): CharString::size() counts the null terminator, and writing it
	// would draw a stray cell and advance the cursor past the end of the text.
	for (int i = 0; i < ascii.length(); ++i) {
		uint8_t cell_bank = bank;
		char code = ascii[i];
		if (ascii[i] == '\x01') {
			if (i + 1 >= ascii.length()) {
				break; // dangling escape, nothing to draw
			}
			if (ascii[i + 1] == '\x01') {
				++i;
				cell_bank = BANK_PATCH;
				code = ascii[i];
			} else {
				bank = (bank == BANK_CP437) ? BANK_PATCH : BANK_CP437;
				continue;
			}
		}
		const cell c = { code, foreground, background, cell_bank, false };
		_screen[pos.y * _con_size.width + pos.x] = c;
		pos.x++;
		if (pos.x == _con_size.width)
			pos = Point2i(0, pos.y + 1);
		if (pos.y == _con_size.height) {
			_scroll_up();
			pos = Point2i(pos.x, pos.y - 1);
		}
	}
	_dirty_screen = true;
	return pos;
}

Point2i TextConsole::_put(const String &p_msg, Point2i pos, ColorIndex foreground, ColorIndex background) {
	ERR_FAIL_COND_V(_screen == 0, pos);
	ERR_FAIL_COND_V(pos.x >= _con_size.width, pos);
	ERR_FAIL_COND_V(pos.y >= _con_size.height, pos);

	// Resolve COLOR_DEFAULT here: it is a sentinel, not a palette entry, and inverting a
	// cell swaps the background into the foreground where it would index palette[] out of
	// bounds.
	if (foreground == COLOR_DEFAULT) {
		foreground = _default_fg_color_index;
	}
	if (background == COLOR_DEFAULT) {
		background = _default_bg_color_index;
	}

	// \x01 toggles the glyph bank for the characters that follow, except that \x01\x01 is
	// not a toggle of a toggle: it draws code 1 of bank 1, which is what keeps that code
	// usable as a glyph slot of its own. Bank 1 holds the patched glyphs, and any code
	// without one is rendered as the inverted bank 0 glyph, see _update_mesh().
	uint8_t bank = BANK_CP437;
	const CharString ascii = p_msg.ascii();
	for (int i = 0; i < ascii.length(); ++i) {
		uint8_t cell_bank = bank;
		char code = ascii[i];
		if (ascii[i] == '\x01') {
			if (i + 1 >= ascii.length()) {
				break; // dangling escape, nothing to draw
			}
			if (ascii[i + 1] == '\x01') {
				++i;
				cell_bank = BANK_PATCH;
				code = ascii[i];
			} else {
				bank = (bank == BANK_CP437) ? BANK_PATCH : BANK_CP437;
				continue;
			}
		}
		const cell c = { code, foreground, background, cell_bank, false };
		if (pos.x < _con_size.width) {
			_screen[pos.y * _con_size.width + pos.x] = c;
			pos.x++;
		}
	}
	_dirty_screen = true;
	return pos;
}

void TextConsole::put_cell(int p_x, int p_y, uint8_t p_code, ColorIndex p_fg, ColorIndex p_bg, Bank p_bank) {
	if (_screen == nullptr) {
		return;
	}
	// Silent clip: a widget draws by poking cells and must not fault on coordinates that
	// fall outside the grid, so out-of-range writes are dropped rather than reported.
	if (p_x < 0 || p_y < 0 || p_x >= _con_size.width || p_y >= _con_size.height) {
		return;
	}
	// COLOR_DEFAULT is a sentinel, not a palette entry; resolve it the way _write()/_put() do.
	if (p_fg == COLOR_DEFAULT) {
		p_fg = _default_fg_color_index;
	}
	if (p_bg == COLOR_DEFAULT) {
		p_bg = _default_bg_color_index;
	}
	const cell c = { char(p_code), p_fg, p_bg, uint8_t(p_bank), false };
	_screen[p_y * _con_size.width + p_x] = c;
	_dirty_screen = true;
}

void TextConsole::put_text(int p_x, int p_y, const String &p_text, ColorIndex p_fg, ColorIndex p_bg) {
	if (_screen == nullptr) {
		return;
	}
	// The same escape grammar as _write()/_put() -- and it must stay in step with them --
	// but every resolved cell goes through put_cell(), so a run that begins off the left
	// edge or overruns the right one simply loses the cells that fall outside instead of
	// wrapping or scrolling. Bank toggles advance nothing, matching the writers.
	uint8_t bank = BANK_CP437;
	const CharString ascii = p_text.ascii();
	int x = p_x;
	for (int i = 0; i < ascii.length(); ++i) {
		uint8_t cell_bank = bank;
		char code = ascii[i];
		if (ascii[i] == '\x01') {
			if (i + 1 >= ascii.length()) {
				break; // dangling escape, nothing to draw
			}
			if (ascii[i + 1] == '\x01') {
				++i;
				cell_bank = BANK_PATCH;
				code = ascii[i];
			} else {
				bank = (bank == BANK_CP437) ? BANK_PATCH : BANK_CP437;
				continue;
			}
		}
		put_cell(x, p_y, uint8_t(code), p_fg, p_bg, Bank(cell_bank));
		++x;
	}
}

void TextConsole::fill_rect(int p_x, int p_y, int p_w, int p_h, uint8_t p_code, ColorIndex p_fg, ColorIndex p_bg, Bank p_bank) {
	for (int dy = 0; dy < p_h; ++dy) {
		for (int dx = 0; dx < p_w; ++dx) {
			put_cell(p_x + dx, p_y + dy, p_code, p_fg, p_bg, p_bank);
		}
	}
}

bool TextConsole::get_cell(int p_x, int p_y, cell &r_cell) const {
	if (_screen == nullptr) {
		return false;
	}
	if (p_x < 0 || p_y < 0 || p_x >= _con_size.width || p_y >= _con_size.height) {
		return false;
	}
	r_cell = _screen[p_y * _con_size.width + p_x];
	return true;
}

void TextConsole::_scroll_up(int p_scroll_lines) {
	ERR_FAIL_COND(p_scroll_lines <= 0);
	ERR_FAIL_COND(_screen == 0);

	const int cell_size = sizeof(cell);
	memmove(_screen, _screen + _con_size.width * p_scroll_lines, (_con_size.height - p_scroll_lines) * _con_size.width * cell_size * p_scroll_lines);
	memset(_screen + (_con_size.height - p_scroll_lines) * _con_size.width, 0, _con_size.width * cell_size * p_scroll_lines);
}

bool TextConsole::_resolve_cell(const cell &p_cell, resolved_cell &r_out) const {
	if (!p_cell.character) {
		return false;
	}

	const uint8_t code = uint8_t(p_cell.character);
	uint8_t fg = p_cell.foreground;
	uint8_t bg = p_cell.background;

	// Bank 1 only carries the patched glyphs. Any other code in that bank is drawn by
	// inverting the bank 0 glyph, which is what makes the \x01 bank toggle behave like the
	// invert marker it replaced.
	uint8_t bank = p_cell.bank;
	bool invert = p_cell.inverted;
	if (bank == BANK_PATCH && !_has_patch[code]) {
		bank = BANK_CP437;
		invert = !invert;
	}

	if (invert) {
		SWAP(fg, bg);
		// Drawing the glyph in a transparent colour would not punch a hole in the
		// background block, it would simply make the character disappear.
		if (fg == COLOR_TRANSPARENT) {
			fg = COLOR_BLACK;
		}
	}

	r_out.code = code;
	r_out.foreground = fg;
	r_out.background = bg;
	r_out.bank = bank;
	return true;
}

void TextConsole::_update_mesh() {
	ERR_FAIL_COND(_screen == 0);

	// Char corners, scaled by pixel_scale. Not `static`: both the face and the zoom can
	// change at runtime, and a cached first-font cell size would freeze the whole grid.
	const Size2i cell_size = get_cell_size();
	const Point2i v0(0, 0); /* 0, 0 */
	const Point2i v1(0, cell_size.height); /* 0, 1 */
	const Point2i v2(cell_size.width, 0); /* 1, 0 */
	const Point2i v3(cell_size.width, cell_size.height); /* 1, 1 */

	PoolVector2Array vertices;
	PoolColorArray bg_colors, fg_colors;
	PoolVector2Array textures;

	Point2i xx;
	cell *p = _screen;
	for (int row = 0; row < _con_size.height; ++row) {
		for (int col = 0; col < _con_size.width; ++col) {
			resolved_cell rc;
			if (_resolve_cell(*p, rc)) {
				const int tex_info = rc.code + rc.bank * 256;
				const uint8_t fg = rc.foreground;
				const uint8_t bg = rc.background;

				vertices.push_back(xx + v0);
				vertices.push_back(xx + v1);
				vertices.push_back(xx + v2);
				vertices.push_back(xx + v1);
				vertices.push_back(xx + v2);
				vertices.push_back(xx + v3);
				// bg:
				bg_colors.push_multi(6, palette[bg]);
				// fg:
				textures.push_back(_chars[tex_info].t[0]);
				textures.push_back(_chars[tex_info].t[1]);
				textures.push_back(_chars[tex_info].t[2]);
				textures.push_back(_chars[tex_info].t[1]);
				textures.push_back(_chars[tex_info].t[2]);
				textures.push_back(_chars[tex_info].t[3]);
				fg_colors.push_multi(6, palette[fg]);
			}
			xx += v2;
			p++;
		}
		xx = Point2i(0, xx.y + cell_size.height);
	}

	Array background, foreground;
	background.resize(VS::ARRAY_MAX);
	background[VS::ARRAY_VERTEX] = vertices;
	background[VS::ARRAY_COLOR] = bg_colors;
	foreground.resize(VS::ARRAY_MAX);
	foreground[VS::ARRAY_VERTEX] = vertices;
	foreground[VS::ARRAY_TEX_UV] = textures;
	foreground[VS::ARRAY_COLOR] = fg_colors;

	if (vertices.size() == 0) {
		_mesh = Ref<ArrayMesh>();
		_mesh_bg = Ref<ArrayMesh>();
	} else {
		// The background surface carries no UVs, so it must be drawn without the glyph atlas
		// bound: otherwise it samples texel (0,0) and is modulated by whatever happens to be
		// there (in the current atlas, the transparent corner of glyph 0).
		_mesh_bg = newref(ArrayMesh);
		_mesh_bg->add_surface_from_arrays(Mesh::PRIMITIVE_TRIANGLES, background, Array(), Mesh::ARRAY_FLAG_USE_2D_VERTICES);
		_mesh = newref(ArrayMesh);
		_mesh->add_surface_from_arrays(Mesh::PRIMITIVE_TRIANGLES, foreground, Array(), Mesh::ARRAY_FLAG_USE_2D_VERTICES);
	}
}

void TextConsole::draw(RID p_canvas_item, const Transform2D &p_xform) {
	ERR_FAIL_COND(!_font_cache[_font_face].is_valid());

	if (_dirty_screen) {
		_update_mesh();
		_dirty_screen = false;
	}

	if (_mesh_bg.is_valid()) {
		VS::get_singleton()->canvas_item_add_mesh(p_canvas_item, _mesh_bg->get_rid(), p_xform, Color(1, 1, 1, 1), RID(), RID());
	}
	if (_mesh.is_valid()) {
		RID texture_rid = _font_cache[_font_face]->get_rid();
		VS::get_singleton()->canvas_item_add_mesh(p_canvas_item, _mesh->get_rid(), p_xform, Color(1, 1, 1, 1), texture_rid, RID());
	}
}

void TextConsole::set_pixel_scale(int p_scale) {
	const int scale = CLAMP(p_scale, 1, CONSOLE_MAX_PIXEL_SCALE);
	if (scale == pixel_scale) {
		return;
	}
	pixel_scale = scale;
	_dirty_screen = true;
}

// Grid limits win over the physical target size: a 27 column console is useless no matter
// how crisp it is. See CONSOLE.md section 6.
static const int CONSOLE_MIN_COLS = 40, CONSOLE_MIN_ROWS = 20, CONSOLE_MAX_COLS = 120;
static const real_t CONSOLE_TARGET_MM = 3.2; // cell height at a natural viewing distance

static int _fit_scale(const Size2i &p_cell, const Size2i &p_viewport, int p_dpi) {
	const real_t px_per_mm = p_dpi / 25.4;
	int scale = CLAMP(int(Math::round(px_per_mm * CONSOLE_TARGET_MM / p_cell.height)), 1, CONSOLE_MAX_PIXEL_SCALE);

	if (p_viewport.width > 0 && p_viewport.height > 0) {
		while (scale > 1 && (p_viewport.width / (p_cell.width * scale) < CONSOLE_MIN_COLS || p_viewport.height / (p_cell.height * scale) < CONSOLE_MIN_ROWS)) {
			scale--; // too zoomed in to fit a usable grid
		}
		while (scale < CONSOLE_MAX_PIXEL_SCALE && p_viewport.width / (p_cell.width * scale) > CONSOLE_MAX_COLS) {
			scale++; // too many columns, the text would be unreadably small
		}
	}
	return scale;
}

static bool _grid_fits(const Size2i &p_cell, const Size2i &p_viewport, int p_scale) {
	if (p_viewport.width <= 0 || p_viewport.height <= 0) {
		return true;
	}
	const int cols = p_viewport.width / (p_cell.width * p_scale);
	const int rows = p_viewport.height / (p_cell.height * p_scale);
	return cols >= CONSOLE_MIN_COLS && cols <= CONSOLE_MAX_COLS && rows >= CONSOLE_MIN_ROWS;
}

void console_auto_font(int p_dpi, const Size2i &p_viewport, TextConsole::FontSize &r_face, int &r_scale) {
	const int dpi = p_dpi > 0 ? p_dpi : 72;

	// 8x12 is the default: the best density/legibility trade-off of the five faces. The
	// others are only reached when the scale knob alone cannot satisfy the grid limits --
	// 4x6 when the screen is too small (or too wide) even at scale 1, 8x16 when it is so
	// dense that the zoom saturates.
	static const TextConsole::FontSize order[] = { TextConsole::DOS_8x12, TextConsole::DOS_4x6, TextConsole::DOS_8x16 };

	for (int i = 0; i < 3; ++i) {
		const Size2i cell = Size2i(embed_debug_font[order[i]].char_w, embed_debug_font[order[i]].char_h);
		const int scale = _fit_scale(cell, p_viewport, dpi);
		if (i == 2 || _grid_fits(cell, p_viewport, scale)) {
			r_face = order[i];
			r_scale = scale;
			return;
		}
	}
}

void TextConsole::logl(const String &p_msg) {
	logl(p_msg, _default_fg_color_index, _default_bg_color_index);
}

void TextConsole::logl(const String &p_msg, ColorIndex foreground, ColorIndex background) {
	// next line
	_cursor_pos = Point2i(0, _put(p_msg, _cursor_pos, foreground, background).y + 1);
	if (_cursor_pos.y == _con_size.height) {
		_scroll_up();
		_cursor_pos = Point2i(0, _cursor_pos.y - 1);
	}
}

void TextConsole::logf(FigFontFace p_face, const String &p_msg) {
	logf(p_face, p_msg, _default_fg_color_index, _default_bg_color_index);
}

/* Resolve the placeholder codes a figlet face renders with into console glyphs.
 *
 * A shape and its inverse share one drawn cell of the glyph sheet, so they only stay
 * distinct characters through smushing by keeping a code of their own until here; the one
 * that comes from bank 1 is written with the \x01 bank toggle. One placeholder is one
 * column either way, so this never changes the width of a rendered row.
 *
 * The toggle is sticky, so it is only emitted where the bank actually changes. Bracketing
 * every bank 1 glyph with its own pair would make the closing toggle of one and the
 * opening toggle of the next collide into \x01\x01, which _put() reads as code 1 of bank
 * 1 -- that inserts a stray cell and leaves the bank latched, so every glyph after it
 * comes out inverted.
 */
static std::string console_resolve_placeholders(const std::string &p_line,
		const char *p_placeholders, const char *p_glyphs, const char *p_bank1) {
	if (!p_placeholders || !p_glyphs) {
		return p_line;
	}
	std::string resolved;
	resolved.reserve(p_line.size());
	bool in_bank1 = false;
	for (size_t i = 0; i < p_line.size(); ++i) {
		const char *at = p_line[i] ? strchr(p_placeholders, p_line[i]) : nullptr;
		const bool is_bank1 = at && p_bank1 && strchr(p_bank1, p_line[i]);
		const char glyph = at ? p_glyphs[at - p_placeholders] : p_line[i];
		// Code 1 has no toggled spelling of its own, so it always takes the literal
		// \x01\x01 form, which draws from bank 1 without disturbing the bank.
		if (is_bank1 && glyph == '\x01') {
			resolved += '\x01';
			resolved += '\x01';
			continue;
		}
		if (is_bank1 != in_bank1) {
			resolved += '\x01';
			in_bank1 = is_bank1;
		}
		resolved += glyph;
	}
	return resolved;
}

void TextConsole::logf(FigFontFace p_face, const String &p_msg, ColorIndex foreground, ColorIndex background) {
	ERR_FAIL_INDEX(p_face, FigFontFaceCount);
	ERR_FAIL_INDEX(foreground, COLOR_COUNT + 1);
	ERR_FAIL_INDEX(background, COLOR_COUNT + 1);

	Figlet::Banner *banner = Figlet::fig_font_mapping[p_face];
	const char *placeholders = banner->placeholderCodes();
	const char *glyphs = banner->glyphCodes();
	const char *bank1 = banner->bank1Characters();

	std::stringstream ss;
	banner->print(&p_msg.ascii()[0], ss);
	std::string line;
	while (std::getline(ss, line, '\n')) {
		line = console_resolve_placeholders(line, placeholders, glyphs, bank1);
		logl(line.c_str(), foreground, background);
	}
}

void TextConsole::logv(const Array &p_log) {
	Array log_msg = p_log;
	while (!log_msg.empty()) {
		String msg = log_msg.pop_front();
		const int foreground = int(log_msg.pop_front());
		const int background = int(log_msg.pop_front());
		logl(msg,
				foreground == COLOR_DEFAULT ? _default_fg_color_index : ColorIndex(foreground),
				background == COLOR_DEFAULT ? _default_bg_color_index : ColorIndex(background));
	}
}

TextConsole::TextConsole() {
	_dirty_screen = false;
	_cursor_pos = Point2i(0, 0);
	_default_bg_color_index = COLOR_TRANSPARENT, _default_fg_color_index = COLOR_WHITE;
	_screen = 0;
	pixel_scale = 1;
	memset(_has_patch, 0, sizeof(_has_patch));
}

TextConsole::~TextConsole() {
	if (_screen)
		memdelete_arr(_screen);
}

#ifdef TOOLS_ENABLED
void ConsoleInstance::_edit_set_position(const Point2 &p_position) {}
Point2 ConsoleInstance::_edit_get_position() const {
	return Point2();
}
void ConsoleInstance::_edit_set_scale(const Size2 &p_scale) {}
Size2 ConsoleInstance::_edit_get_scale() const {
	return Size2();
}
#endif

Transform2D ConsoleInstance::get_transform() const {
	return Transform2D();
}

void ConsoleInstance::_adopt_secondary_geometry(const Size2i &p_size, int p_dpi) {
	ERR_FAIL_COND(!console.is_valid());

	if (auto_font) {
		console_auto_font(p_dpi, p_size, font_face, pixel_scale);
		console->load_font(font_face);
		console->set_pixel_scale(pixel_scale);
	}

	const Size2i cell = console->get_cell_size();
	ERR_FAIL_COND(cell.width <= 0 || cell.height <= 0);
	console->resize(MAX(1, p_size.width / cell.width), MAX(1, p_size.height / cell.height));

	dirty = true;
}

ConsoleInstance::SecondaryMode ConsoleInstance::_secondary_mode_setting() {
	static int cached = -1;
	if (cached == -1) {
		GLOBAL_DEF("debug/console/secondary_display", "auto");
		ProjectSettings::get_singleton()->set_custom_property_info("debug/console/secondary_display",
				PropertyInfo(Variant::STRING, "debug/console/secondary_display", PROPERTY_HINT_ENUM, "auto,always,never"));
		const String mode = GLOBAL_GET("debug/console/secondary_display");
		if (mode.nocasecmp_to("always") == 0) {
			cached = SECONDARY_ALWAYS;
		} else if (mode.nocasecmp_to("never") == 0) {
			cached = SECONDARY_NEVER;
		} else {
			cached = SECONDARY_AUTO;
		}
	}
	return SecondaryMode(cached);
}

void ConsoleInstance::_poll_secondary_touch() {
	SecondaryDisplay *display = SecondaryDisplay::get_singleton();
	if (!display || secondary_mode == SECONDARY_NEVER) {
		return;
	}

	if (!panel_touch) {
		// Opt-out by default: a panel that reacts to taps is a panel the player can hit by
		// accident, and on some platforms its window competes with the game for input focus.
		// The queue is still drained so enabling it later does not replay old taps.
		SecondaryDisplay::TouchEvent discarded;
		while (display->pop_touch(discarded)) {
		}
		touch_down = false;
		return;
	}

	// The threshold is generous: the panel is usually a small strip and a deliberate
	// "hide" gesture should not be triggered by a slow page tap.
	static int long_press_msec = -1;
	if (long_press_msec == -1) {
		long_press_msec = MAX(100, (int)GLOBAL_DEF("debug/console/long_press_msec", 600));
	}

	SecondaryDisplay::TouchEvent ev;
	while (display->pop_touch(ev)) {
		if (ev.pressed) {
			touch_down = true;
			touch_down_msec = ev.time_msec;
			continue;
		}
		if (!touch_down) {
			continue; // release without a matching press (surface was re-attached)
		}
		touch_down = false;
		const uint64_t held = ev.time_msec > touch_down_msec ? ev.time_msec - touch_down_msec : 0;
		const bool long_press = (int)held >= long_press_msec;
		if (!is_visible_in_tree()) {
			// Any tap brings a long-press-hidden console back; there is no other way in
			// on a device whose only input is this panel.
			if (!long_press) {
				set_visible(true);
				dirty = true;
			}
		} else if (long_press) {
			set_visible(false);
		} else {
			next_page();
		}
	}
}

void ConsoleInstance::_blank_secondary() {
	SecondaryDisplay *display = SecondaryDisplay::get_singleton();
	if (!display || secondary_mode == SECONDARY_NEVER || !display->is_available()) {
		return;
	}
	if (!secondary_active) {
		return; // never took the panel over, nothing of ours is on it
	}
	int stride_px = 0;
	Size2i locked;
	uint32_t *bits = display->lock_buffer(stride_px, locked);
	if (!bits) {
		return;
	}
	for (int y = 0; y < locked.height; ++y) {
		uint32_t *row = bits + y * stride_px;
		for (int x = 0; x < locked.width; ++x) {
			row[x] = 0xff000000;
		}
	}
	display->unlock_and_post();
}

void ConsoleInstance::_present_secondary() {
	SecondaryDisplay *display = SecondaryDisplay::get_singleton();
	if (secondary_mode == SECONDARY_NEVER) {
		display = nullptr; // the panel is opted out of; stay an overlay
	}
	if (!display || !display->is_available()) {
		if (secondary_active) {
			// The panel was unplugged: fall back to the main viewport geometry.
			secondary_active = false;
			secondary_size = Size2i();
			_auto_select_font();
			_apply_font();
			update(); // the overlay takes over again
		}
		return;
	}

	const Size2i size = display->get_size();
	if (!secondary_active || secondary_size != size) {
		const bool was_active = secondary_active;
		secondary_active = true;
		secondary_size = size;
		_adopt_secondary_geometry(size, display->get_dpi());
		if (!was_active) {
			update(); // clear whatever the overlay had drawn on the game viewport
		}
	}
	if (dirty) {
		_render();
	}

	int stride_px = 0;
	Size2i locked;
	uint32_t *bits = display->lock_buffer(stride_px, locked);
	if (!bits) {
		return;
	}

	// The console leaves COLOR_TRANSPARENT cells untouched, so the panel gets an opaque
	// black background of its own rather than whatever the surface held before.
	for (int y = 0; y < locked.height; ++y) {
		uint32_t *row = bits + y * stride_px;
		for (int x = 0; x < locked.width; ++x) {
			row[x] = 0xff000000; // opaque black, same bytes in ARGB32 and ABGR32
		}
	}
	console_blit(**console, bits, stride_px, locked.width, locked.height, CONSOLE_PIXEL_ABGR32);

	display->unlock_and_post();
}

// Everything a console needs before it can render, with no dependency on the scene tree:
// the grid, the logger claim, and the banner. Shared by NOTIFICATION_ENTER_TREE and
// render_offscreen(). Idempotent.
void ConsoleInstance::_bootstrap() {
	if (!console.is_valid()) {
		console = newref(TextConsole);
		if (auto_font) {
			// An explicit set_font()/set_pixel_scale() made before the first render pins the
			// choice, exactly as one made afterwards does.
			_auto_select_font();
		}
		_apply_font();
	}
	{
		MutexLock lock(active_mutex);
		active = this;
		_drain_backlog();
	}
	if (log_lines.empty()) {
		Vector<String> text;
		Vector<int> color;
		console_banner_lines(text, color);
		for (int i = 0; i < text.size(); ++i) {
			_push_line(text[i], TextConsole::ColorIndex(color[i]), TextConsole::COLOR_DEFAULT);
		}
	}
}

void ConsoleInstance::render_offscreen(int p_cols, int p_rows) {
	_bootstrap();
	ERR_FAIL_COND(!console.is_valid());
	if (p_cols > 0 && p_rows > 0) {
		console->resize(p_cols, p_rows);
	}
	_render(); // update() is a no-op outside the tree, so this only touches the grid
}

void ConsoleInstance::_notification(int p_notification) {
	switch (p_notification) {
		case NOTIFICATION_ENTER_TREE: {
			_bootstrap();
			if (Viewport *viewport = get_viewport()) {
				if (!viewport->is_connected("size_changed", this, "_viewport_size_changed")) {
					viewport->connect("size_changed", this, "_viewport_size_changed");
				}
			}
			set_process_internal(true);
			_render();
		} break;

		case NOTIFICATION_INTERNAL_PROCESS: {
			_poll_secondary_touch();
			if (!is_visible_in_tree()) {
				// Hidden by a long press: keep draining touches (a tap brings it back) but
				// leave the panel blank rather than a frozen snapshot.
				_blank_secondary();
				break;
			}
			// PAGE_LOG only redraws when something was logged; the polled pages tick at
			// refresh_rate so a busy watch table cannot eat the frame budget.
			const real_t delta = get_process_delta_time();
			refresh_accum += delta;
			const real_t period = refresh_rate > 0 ? 1.0 / refresh_rate : 0.2;
			if (refresh_accum >= period) {
				refresh_accum = 0;
				if (page != PAGE_LOG) {
					_poll_watches();
					dirty = true;
				}
			}
			if (dirty) {
				_render();
			}
			_present_secondary();
		} break;

		case NOTIFICATION_EXIT_TREE: {
			{
				MutexLock lock(active_mutex);
				if (active == this) {
					active = nullptr;
				}
			}
			if (Viewport *viewport = get_viewport()) {
				if (viewport->is_connected("size_changed", this, "_viewport_size_changed")) {
					viewport->disconnect("size_changed", this, "_viewport_size_changed");
				}
			}
		} break;

		case NOTIFICATION_DRAW: {
			// While the auxiliary panel owns the console the game viewport is left clean;
			// drawing both would show the same text twice (CONSOLE.md section 11).
			// "always" keeps the game screen clean even when no panel is attached.
			if (secondary_active || secondary_mode == SECONDARY_ALWAYS) {
				break;
			}
			if (console.is_valid()) {
				console->draw(get_canvas_item(), get_global_transform().affine_inverse());
			}
		} break;
	}
}

void ConsoleInstance::console_msg(const String &p_msg) {
	// parse control characters; the parsed lines land in the ring buffer, not on the grid
	_process_codes(p_msg);
	if (page == PAGE_LOG) {
		_render();
	}
}

namespace {

struct ConsoleMarkupRun {
	String text;
	TextConsole::ColorIndex foreground;
	TextConsole::ColorIndex background;
};

const char *const console_color_names[] = {
	"black",
	"blue",
	"green",
	"cyan",
	"red",
	"magenta",
	"brown",
	"lightgray",
	"darkgray",
	"lightblue",
	"lightgreen",
	"lightcyan",
	"lightred",
	"lightmagenta",
	"yellow",
	"white",
	"transparent",
	"default",
};

int console_color_index(const String &p_name) {
	for (int c = 0; c < TextConsole::COLOR_COUNT; ++c) {
		if (p_name == console_color_names[c]) {
			return c;
		}
	}
	return -1;
}

// Parses the console's BBCode-like markup ("[fg=red]hot[/fg]") into coloured runs.
//
// Anything that merely looks like a tag -- "[Leaderboard] ready", "[WARN]", "[0]" -- is
// emitted verbatim. The engine and the game log such lines constantly, so a malformed or
// unknown tag must be a no-op, never a stall: every path through the loop below advances
// `pos`, and the guard at the bottom turns any future regression into a dropped tag
// instead of a frozen application.
void console_parse_markup(const String &p_text, Vector<ConsoleMarkupRun> &r_runs) {
	List<String> tag_stack;
	TextConsole::ColorIndex fg = TextConsole::COLOR_DEFAULT;
	TextConsole::ColorIndex bg = TextConsole::COLOR_DEFAULT;
	const int length = p_text.length();
	int pos = 0;

	while (pos < length) {
		const int start = pos;

		int brk_pos = p_text.find("[", pos);
		if (brk_pos < 0) {
			brk_pos = length;
		}
		if (brk_pos > pos) {
			ConsoleMarkupRun run;
			run.text = p_text.substr(pos, brk_pos - pos);
			run.foreground = fg;
			run.background = bg;
			r_runs.push_back(run);
		}
		if (brk_pos == length) {
			break; // nothing else to add
		}

		const int brk_end = p_text.find("]", brk_pos + 1);
		if (brk_end == -1) {
			// Unterminated: the rest of the line is plain text.
			ConsoleMarkupRun run;
			run.text = p_text.substr(brk_pos, length - brk_pos);
			run.foreground = fg;
			run.background = bg;
			r_runs.push_back(run);
			break;
		}

		const String tag = p_text.substr(brk_pos + 1, brk_end - brk_pos - 1);
		pos = brk_end + 1; // unconditional progress; branches below only adjust state

		bool handled = false;
		if (tag.begins_with("/")) {
			const String closed = tag.substr(1, tag.length());
			if (tag_stack.size() && tag_stack.front()->get() == closed) {
				if (closed == "fg") {
					fg = TextConsole::COLOR_DEFAULT;
				} else if (closed == "bg") {
					bg = TextConsole::COLOR_DEFAULT;
				}
				tag_stack.pop_front();
				handled = true;
			}
		} else if (tag.begins_with("fg=") || tag.begins_with("bg=")) {
			const int color_index = console_color_index(tag.substr(3, tag.length()));
			if (color_index != -1) {
				if (tag.begins_with("fg=")) {
					fg = TextConsole::ColorIndex(color_index);
				} else {
					bg = TextConsole::ColorIndex(color_index);
				}
				tag_stack.push_front(tag.substr(0, 2));
				handled = true;
			}
		}

		if (!handled) {
			// Unknown, mismatched or malformed: pass it through as ordinary text. Warning
			// here would re-enter the logger that produced this very line.
			ConsoleMarkupRun run;
			run.text = "[" + tag + "]";
			run.foreground = fg;
			run.background = bg;
			r_runs.push_back(run);
		}

		if (pos <= start) {
			// Unreachable by construction. Kept because a parser that can stall would hang
			// the whole engine on a stray bracket, which is far worse than losing a tag.
			ERR_PRINT("Console markup parser failed to advance; dropping the rest of the line.");
			break;
		}
	}
}

} // namespace

Error ConsoleInstance::_process_codes(const String &p_concodes) {
	Vector<ConsoleMarkupRun> runs;
	console_parse_markup(p_concodes, runs);
	for (int i = 0; i < runs.size(); ++i) {
		_append_segment(runs[i].text, runs[i].foreground, runs[i].background);
	}
	_flush_line();
	return OK;
}

void ConsoleInstance::_viewport_size_changed() {
	if (!console.is_valid()) {
		return;
	}
	if (secondary_active) {
		return; // the auxiliary screen owns the geometry while it is attached
	}
	// An explicit set_font()/set_pixel_scale() pins the choice; otherwise the face and zoom
	// are re-derived for the new viewport.
	if (auto_font) {
		_auto_select_font();
	}
	_apply_font();
	update();
}

void ConsoleInstance::_auto_select_font() {
	const Viewport *viewport = get_viewport();
	const Size2i size = viewport ? Size2i(viewport->get_visible_rect().size) : Size2i();
	const int dpi = OS::get_singleton()->get_screen_dpi(OS::get_singleton()->get_current_screen());
	console_auto_font(dpi, size, font_face, pixel_scale);
}

void ConsoleInstance::_apply_font() {
	ERR_FAIL_COND(!console.is_valid());

	console->load_font(font_face);
	console->set_pixel_scale(pixel_scale);

	// Reflows the grid to whichever screen currently owns the geometry.
	if (secondary_active) {
		const Size2i cell = console->get_cell_size();
		if (cell.width > 0 && cell.height > 0) {
			console->resize(MAX(1, secondary_size.width / cell.width), MAX(1, secondary_size.height / cell.height));
		}
	} else {
		const Viewport *viewport = get_viewport();
		if (!viewport || !console->resize(viewport)) {
			console->resize(80, 25); // default size
		}
	}

	// The grid was just thrown away; the ring buffer and the watch table are the source of
	// truth, so the current page is simply drawn again.
	if (is_inside_tree()) {
		_render();
	}
}

void ConsoleInstance::console_resize(const Viewport *p_view) {
	ERR_FAIL_COND(!console.is_valid());
	if (!p_view || !console->resize(p_view)) {
		console->resize(80, 25);
	}
	update();
}

void ConsoleInstance::set_font(TextConsole::FontSize p_font) {
	ERR_FAIL_INDEX(p_font, TextConsole::DosFontCount);
	auto_font = false;
	font_face = p_font;
	if (console.is_valid()) {
		_apply_font();
		update();
	}
}

TextConsole::FontSize ConsoleInstance::get_font() const {
	return font_face;
}

void ConsoleInstance::next_font() {
	set_font(TextConsole::FontSize((font_face + 1) % TextConsole::DosFontCount));
}

void ConsoleInstance::set_pixel_scale(int p_scale) {
	auto_font = false;
	pixel_scale = CLAMP(p_scale, 1, CONSOLE_MAX_PIXEL_SCALE);
	if (console.is_valid()) {
		_apply_font();
		update();
	}
}

int ConsoleInstance::get_pixel_scale() const {
	return pixel_scale;
}

void ConsoleInstance::set_auto_font(bool p_enabled) {
	auto_font = p_enabled;
	if (auto_font && console.is_valid()) {
		_auto_select_font();
		_apply_font();
		update();
	}
}

bool ConsoleInstance::is_auto_font() const {
	return auto_font;
}

ConsoleInstance *ConsoleInstance::active = nullptr;
Mutex ConsoleInstance::active_mutex;
Vector<ConsoleInstance::LogSegment> ConsoleInstance::backlog;

void ConsoleInstance::_append_segment(const String &p_text, TextConsole::ColorIndex p_fg, TextConsole::ColorIndex p_bg) {
	// Embedded newlines break the run into several lines; everything else accumulates into
	// the line currently being assembled.
	const Vector<String> parts = p_text.split("\n", true);
	for (int i = 0; i < parts.size(); ++i) {
		if (!parts[i].empty()) {
			LogSegment seg;
			seg.text = parts[i];
			seg.foreground = p_fg;
			seg.background = p_bg;
			pending.push_back(seg);
		}
		if (i + 1 < parts.size()) {
			_flush_line();
		}
	}
}

void ConsoleInstance::_flush_line() {
	_commit_line(pending);
	pending.clear();
}

void ConsoleInstance::_commit_line(const Vector<LogSegment> &p_segments) {
	LogLine line;
	line.segments = p_segments;

	MutexLock lock(log_mutex);
	log_lines.push_back(line);
	if (log_lines.size() > log_capacity) {
		// Trim in blocks: a Vector erase is O(n), and dropping one line per message on a
		// full buffer would make logging quadratic.
		const int drop = log_lines.size() - log_capacity + log_capacity / 4;
		Vector<LogLine> kept;
		kept.resize(log_lines.size() - drop);
		for (int i = 0; i < kept.size(); ++i) {
			kept.write[i] = log_lines[i + drop];
		}
		log_lines = kept;
	}
	dirty = true;
}

void ConsoleInstance::log_from_thread(const String &p_text, TextConsole::ColorIndex p_fg, TextConsole::ColorIndex p_bg) {
	MutexLock lock(active_mutex);

	LogSegment seg;
	seg.text = p_text;
	seg.foreground = p_fg;
	seg.background = p_bg;

	if (!active) {
		// The engine logs from the moment Main registers ConsoleLogger, long before any
		// scene (and therefore any ConsoleInstance) exists. Those lines -- driver banners,
		// resource loading, early script errors -- are exactly the interesting ones on a
		// device, so they are kept here and flushed by the first instance to enter the tree.
		if (backlog.size() >= backlog_capacity) {
			backlog.remove(0);
		}
		backlog.push_back(seg);
		return;
	}
	Vector<LogSegment> segments;
	segments.push_back(seg);
	active->_commit_line(segments);
}

// Called under `active_mutex` with `active` already set.
void ConsoleInstance::_drain_backlog() {
	for (int i = 0; i < backlog.size(); ++i) {
		Vector<LogSegment> segments;
		segments.push_back(backlog[i]);
		_commit_line(segments);
	}
	backlog.clear();
}

void ConsoleInstance::_push_line(const String &p_text, TextConsole::ColorIndex p_fg, TextConsole::ColorIndex p_bg) {
	_append_segment(p_text, p_fg, p_bg);
	_flush_line();
}

void ConsoleInstance::_push_raw_line(const String &p_text, TextConsole::ColorIndex p_fg, TextConsole::ColorIndex p_bg) {
	// Deliberately skips _append_segment(): that splits on "\n" because log *text* may carry
	// embedded newlines, but this string is an already-rendered grid row, where 0x0a is just
	// the CP437 glyph of that code -- several figlet faces use it, along with 0x08 and 0x0b.
	// Splitting there tore each row apart and left the bank toggles unbalanced.
	if (!pending.empty()) {
		_flush_line(); // keep ordering against a partially assembled line
	}
	LogSegment seg;
	seg.text = p_text;
	seg.foreground = p_fg;
	seg.background = p_bg;
	Vector<LogSegment> segments;
	segments.push_back(seg);
	_commit_line(segments);
}

int ConsoleInstance::_find_watch(const StringName &p_name) const {
	for (int i = 0; i < watches.size(); ++i) {
		if (watches[i].name == p_name) {
			return i;
		}
	}
	return -1;
}

String ConsoleInstance::_format_value(const Variant &p_value) const {
	switch (p_value.get_type()) {
		case Variant::REAL: {
			return String::num(double(p_value), 3);
		} break;
		case Variant::VECTOR2: {
			const Vector2 v = p_value;
			return vformat("%s, %s", String::num(v.x, 2), String::num(v.y, 2));
		} break;
		case Variant::VECTOR3: {
			const Vector3 v = p_value;
			return vformat("%s, %s, %s", String::num(v.x, 2), String::num(v.y, 2), String::num(v.z, 2));
		} break;
		case Variant::NIL: {
			return "<nil>";
		} break;
		default: {
		}
	}
	return String(p_value);
}

void ConsoleInstance::_poll_watches() {
	for (int i = 0; i < watches.size(); ++i) {
		Watch &w = watches.write[i];

		if (w.getter.is_valid()) {
			if (w.getter->is_valid()) {
				Variant::CallError err;
				const Variant *argv = nullptr;
				w.cached = w.getter->call_func(&argv, 0, err);
			} else {
				w.cached = "<invalid funcref>";
			}
		} else if (w.obj) {
			// ObjectDB, not a stored pointer: a freed node drops its row instead of
			// dereferencing dangling memory.
			Object *obj = ObjectDB::get_instance(w.obj);
			if (!obj) {
				watches.remove(i--);
				continue;
			}
			bool valid = false;
			const Variant value = obj->get(w.property, &valid);
			w.cached = valid ? value : Variant("<no property>");
		}
	}
}

void ConsoleInstance::_render_header() {
	static const char *page_names[PAGE_MAX] = { "LOG", "SYSINFO", "PROPS" };

	const int cols = console->get_console_size().width;
	String left = vformat(" [%d/%d] %s", int(page) + 1, int(PAGE_MAX), page_names[page]);
	String right = vformat("%d fps  %dx%d ", Engine::get_singleton()->get_frames_per_second(),
			console->get_console_size().width, console->get_console_size().height);

	String header = left;
	const int pad = cols - left.length() - right.length();
	for (int i = 0; i < pad; ++i) {
		header += " ";
	}
	header += right;
	if (header.length() > cols) {
		header = header.substr(0, cols);
	}
	console->logl(header, TextConsole::COLOR_BLACK, TextConsole::COLOR_LIGHTGRAY);
}

namespace {

/* Walks a console string under the same escape grammar as TextConsole::_put() and stops
 * once p_max_cells grid cells have been consumed, returning how many *characters* that
 * took. A lone \x01 toggles the glyph bank and draws nothing, while \x01\x01 spends two
 * characters on a single cell, so string length is not display width -- every figlet line
 * is full of bank toggles, and measuring it with length() wrapped them to a fraction of
 * the real width. r_bank carries the bank state out so a continuation row can re-open it;
 * r_cells reports the cells actually consumed. Must stay in step with _put()/put_text().
 */
int console_measure(const String &p_text, int p_max_cells, bool &r_bank, int &r_cells) {
	const int length = p_text.length();
	int i = 0;
	int cells = 0;
	while (i < length && cells < p_max_cells) {
		if (p_text[i] != 0x01) {
			++i;
			++cells;
			continue;
		}
		if (i + 1 >= length) {
			i = length; // dangling escape: _put() stops here and draws nothing
			break;
		}
		if (p_text[i + 1] == 0x01) {
			i += 2; // escaped literal, one cell out of two characters
			++cells;
		} else {
			++i; // bank toggle, no cell
			r_bank = !r_bank;
		}
	}
	// Absorb toggles sitting exactly on the break, so they take effect on this row rather
	// than dangling at the head of the next one.
	while (i + 1 < length && p_text[i] == 0x01 && p_text[i + 1] != 0x01) {
		++i;
		r_bank = !r_bank;
	}
	r_cells = cells;
	return i;
}

} // namespace

void ConsoleInstance::_wrap_line(const LogLine &p_line, int p_width, Vector<LogLine> &r_rows) const {
	const int width = MAX(1, p_width);
	LogLine row;
	int used = 0;
	bool bank = false; // grid bank state, carried across the wrap points

	for (int i = 0; i < p_line.segments.size(); ++i) {
		LogSegment seg = p_line.segments[i];
		while (true) {
			bool next_bank = bank;
			int cells = 0;
			const int cut = console_measure(seg.text, width - used, next_bank, cells);
			if (cut > 0) {
				LogSegment head = seg;
				head.text = seg.text.substr(0, cut);
				row.segments.push_back(head);
			}
			used += cells;
			bank = next_bank;
			if (cut >= seg.text.length()) {
				break;
			}
			seg.text = seg.text.substr(cut, seg.text.length() - cut);

			r_rows.push_back(row);
			row = LogLine();
			used = 0;
			if (bank) {
				// Each row is drawn by its own _put() call, which always starts in bank 0.
				LogSegment reopen = seg;
				reopen.text = String::chr(0x01);
				row.segments.push_back(reopen);
			}
		}
	}
	r_rows.push_back(row); // an empty line still occupies a row
}

void ConsoleInstance::_render_log() {
	MutexLock lock(log_mutex);

	const Size2i size = console->get_console_size();
	const int rows = size.height - 1; // the header takes one row

	// Wrap from the newest line backwards, so a long error keeps its tail on screen instead
	// of pushing everything else off.
	Vector<LogLine> visible;
	for (int i = log_lines.size() - 1; i >= 0 && visible.size() < rows; --i) {
		Vector<LogLine> wrapped;
		_wrap_line(log_lines[i], size.width, wrapped);
		for (int j = wrapped.size() - 1; j >= 0 && visible.size() < rows; --j) {
			visible.push_back(wrapped[j]);
		}
	}

	for (int i = visible.size() - 1; i >= 0; --i) {
		const LogLine &line = visible[i];
		Point2i pos = console->get_cursor();
		for (int j = 0; j < line.segments.size(); ++j) {
			pos = console->_put(line.segments[j].text, pos, line.segments[j].foreground, line.segments[j].background);
		}
		console->set_cursor(Point2i(0, pos.y + 1));
	}
}

// --- SYSINFO collectors -----------------------------------------------------------------
//
// Everything here is polled at `refresh_rate` (~5 Hz), so the cost budget per item is a
// syscall or two. Anything that cannot change while the process runs -- the SoC name, the
// GL strings, the thermal zone list -- is resolved once and cached in a function-local
// static instead.

namespace {

#if defined(__linux__) || defined(ANDROID_ENABLED)

// Lines of a /proc or /sys pseudo-file, empty when it cannot be read.
//
// These deliberately bypass FileAccess: on Android ACCESS_FILESYSTEM is served by
// FileAccessFilesystemJAndroid, which routes through the Java storage API and cannot see
// kernel pseudo-files at all. Their reported size is also 0, so only stdio streaming works.
Vector<String> console_read_sys_file(const String &p_path, int p_max_lines = 4096) {
	Vector<String> lines;
	FILE *f = fopen(p_path.utf8().get_data(), "rb");
	if (!f) {
		return lines;
	}
	char buf[512];
	while (lines.size() < p_max_lines && fgets(buf, sizeof(buf), f)) {
		lines.push_back(String::utf8(buf).strip_edges());
	}
	fclose(f);
	return lines;
}

String console_read_sys_line(const String &p_path) {
	const Vector<String> lines = console_read_sys_file(p_path, 1);
	return lines.empty() ? String() : lines[0];
}

#endif

// First line of /proc/cpuinfo that names the part. Android drops "model name" on arm, so
// "Hardware" and "Processor" are tried as well; empty when nothing matched.
String console_cpu_model() {
	static String cached;
	static bool resolved = false;
	if (resolved) {
		return cached;
	}
	resolved = true;
#if defined(__linux__) || defined(ANDROID_ENABLED)
	const Vector<String> lines = console_read_sys_file("/proc/cpuinfo");
	for (int i = 0; i < lines.size(); ++i) {
		const String &line = lines[i];
		const int colon = line.find(":");
		if (colon < 0) {
			continue;
		}
		const String key = line.substr(0, colon).strip_edges();
		if (key == "Hardware" || key == "model name" || key == "Processor") {
			cached = line.substr(colon + 1).strip_edges();
			if (key == "Hardware") {
				break; // the most specific of the three on Android
			}
		}
	}
#endif
	return cached;
}

// Highest CPU/SoC die temperature in degrees Celsius, or -1 when unavailable. Qualcomm
// parts expose a hundred zones, so the interesting ones are picked once by type.
float console_cpu_temperature() {
#if defined(__linux__) || defined(ANDROID_ENABLED)
	static Vector<String> zones;
	static bool resolved = false;
	if (!resolved) {
		resolved = true;
		DIR *d = opendir("/sys/class/thermal");
		if (d) {
			while (struct dirent *ent = readdir(d)) {
				const String name = String::utf8(ent->d_name);
				if (!name.begins_with("thermal_zone")) {
					continue;
				}
				const String base = "/sys/class/thermal/" + name;
				const String type = console_read_sys_line(base + "/type").to_lower();
				// "cpu*", "*-usr" (tsens), "soc" -- skip battery/charger/skin zones, which
				// say nothing about how hard the chip is being pushed.
				if (type.find("cpu") >= 0 || type.find("soc") >= 0) {
					zones.push_back(base + "/temp");
				}
				if (zones.size() >= 8) {
					break;
				}
			}
			closedir(d);
		}
	}

	float best = -1;
	for (int i = 0; i < zones.size(); ++i) {
		const String raw = console_read_sys_line(zones[i]);
		if (raw.is_valid_integer()) {
			// Millidegrees on every sane kernel, but a few report plain degrees.
			const int64_t v = raw.to_int64();
			const float c = v > 1000 ? v / 1000.0f : float(v);
			best = MAX(best, c);
		}
	}
	return best;
#else
	return -1;
#endif
}

// MemAvailable / MemTotal in bytes; both zero when /proc/meminfo is not readable.
void console_system_memory(uint64_t &r_avail, uint64_t &r_total) {
	r_avail = 0;
	r_total = 0;
#if defined(__linux__) || defined(ANDROID_ENABLED)
	const Vector<String> lines = console_read_sys_file("/proc/meminfo", 64);
	for (int i = 0; i < lines.size() && (!r_avail || !r_total); ++i) {
		const String &line = lines[i];
		const int colon = line.find(":");
		if (colon < 0) {
			continue;
		}
		const String key = line.substr(0, colon).strip_edges();
		if (key != "MemAvailable" && key != "MemTotal") {
			continue;
		}
		// "MemTotal:       11534336 kB"
		const String value = line.substr(colon + 1).strip_edges().split(" ")[0];
		if (!value.is_valid_integer()) {
			continue;
		}
		const uint64_t bytes = uint64_t(value.to_int64()) * 1024;
		if (key == "MemAvailable") {
			r_avail = bytes;
		} else {
			r_total = bytes;
		}
	}
#endif
}

// Free bytes on the volume holding the user data dir, or 0 when it cannot be determined.
uint64_t console_storage_free() {
#if defined(UNIX_ENABLED) && !defined(NO_STATVFS)
	const CharString path = OS::get_singleton()->get_user_data_dir().utf8();
	struct statvfs st;
	if (statvfs(path.get_data(), &st) == 0) {
		return uint64_t(st.f_bavail) * uint64_t(st.f_frsize);
	}
#endif
	return 0;
}

String console_power_line() {
	OS *os = OS::get_singleton();
	const int percent = os->get_power_percent_left();
	if (percent < 0) {
		return String();
	}
	String state;
	switch (os->get_power_state()) {
		case OS::POWERSTATE_CHARGING:
			state = " chg";
			break;
		case OS::POWERSTATE_CHARGED:
			state = " full";
			break;
		case OS::POWERSTATE_ON_BATTERY:
			state = " bat";
			break;
		default:
			break;
	}
	return itos(percent) + "%" + state;
}

// 85300 -> "85.3 K"; keeps wide counters inside one column on a 40-cell panel.
String console_format_count(double p_value) {
	if (p_value >= 1000000.0) {
		return vformat("%.1f M", p_value / 1000000.0);
	}
	if (p_value >= 1000.0) {
		return vformat("%.1f K", p_value / 1000.0);
	}
	return itos(int64_t(p_value));
}

double console_perf(Performance::Monitor p_monitor) {
	const Performance *perf = Performance::get_singleton();
	return perf ? perf->get_monitor(p_monitor) : 0;
}

} // namespace

void ConsoleInstance::_render_sysinfo() {
	OS *os = OS::get_singleton();
	VisualServer *vs = VisualServer::get_singleton();
	const int screen = os->get_current_screen();
	const int width = console->get_console_size().width;

	// A helper for the "name  value" rows; the label column is fixed so the values line up.
	struct Row {
		TextConsole *con;
		void operator()(const char *p_label, const String &p_value, TextConsole::ColorIndex p_color = TextConsole::COLOR_DEFAULT) {
			String label = String(" ") + p_label;
			while (label.length() < 10) {
				label += " ";
			}
			con->logl(label + p_value, p_color);
		}
	} row = { *console };

	String version = VERSION_FULL_NAME;
	if (String(VERSION_HASH).length() >= 7) {
		version += " [" + String(VERSION_HASH).substr(0, 7) + "]";
	}
	console->logl(version, TextConsole::COLOR_WHITE);

	// --- device ---------------------------------------------------------------------
	String device = os->get_name();
	if (!os->get_model_name().empty() && os->get_model_name() != "GenericDevice") {
		device += " / " + os->get_model_name();
	}
	row("device", device);

	String cpu = itos(os->get_processor_count()) + " cores";
	const String cpu_model = console_cpu_model();
	if (!cpu_model.empty()) {
		cpu += "  " + cpu_model;
	}
	row("cpu", cpu);

	const float temp = console_cpu_temperature();
	String status;
	if (temp >= 0) {
		status = vformat("%.1f C", temp);
	}
	const String power = console_power_line();
	if (!power.empty()) {
		status += status.empty() ? power : "   batt " + power;
	}
	if (!status.empty()) {
		// Warm silicon means the frame times below are already being throttled.
		row("thermal", status, temp >= 80 ? TextConsole::COLOR_LIGHTRED : (temp >= 65 ? TextConsole::COLOR_YELLOW : TextConsole::COLOR_DEFAULT));
	}

	String gpu = vs ? vs->get_video_adapter_name() : String();
	if (gpu.empty()) {
		gpu = os->get_video_driver_name(os->get_current_video_driver());
	} else {
		gpu += " (" + String(os->get_video_driver_name(os->get_current_video_driver())) + ")";
	}
	row("gpu", gpu);
	row("locale", os->get_locale());

	// --- displays -------------------------------------------------------------------
	row("screen", vformat("%dx%d @ %d dpi", int(os->get_screen_size(screen).width), int(os->get_screen_size(screen).height), os->get_screen_dpi(screen)));
	if (SecondaryDisplay *sd = SecondaryDisplay::get_singleton()) {
		if (sd->is_available()) {
			// The panel this console is most likely being read on.
			row("panel", vformat("%dx%d @ %d dpi", sd->get_size().width, sd->get_size().height, sd->get_dpi()), TextConsole::COLOR_LIGHTCYAN);
		}
	}
	row("console", vformat("%dx%d cells, %s, scale %d", console->get_console_size().width, console->get_console_size().height, embed_debug_font[console->get_font()].image, console->get_pixel_scale()));

	// --- frame ----------------------------------------------------------------------
	console->logl(String(BOX_SLR).repeat(MAX(1, width)), TextConsole::COLOR_DARKGRAY);

	const float fps = console_perf(Performance::TIME_FPS);
	row("fps", vformat("%d   frame %.1f ms   phys %.1f ms", int(fps), console_perf(Performance::TIME_PROCESS) * 1000.0, console_perf(Performance::TIME_PHYSICS_PROCESS) * 1000.0));

	// Plot the fps history under the numbers: the instantaneous value says nothing about
	// whether a stutter just happened. The range is pinned to 0..60 so the plot means the
	// same thing frame to frame instead of auto-scaling to whatever the recent spread was.
	fps_history.push_back(fps);
	while (fps_history.size() > fps_history_capacity) {
		fps_history.remove(0);
	}
	const int plot_width = MAX(8, MIN(width - 12, fps_history_capacity));
	row("", graph(fps_history, plot_width, 0.0, 60.0), TextConsole::COLOR_LIGHTGREEN);
	row("draws", vformat("%d   verts %s   objs %d", int(console_perf(Performance::RENDER_DRAW_CALLS_IN_FRAME)), console_format_count(console_perf(Performance::RENDER_VERTICES_IN_FRAME)), int(console_perf(Performance::RENDER_OBJECTS_IN_FRAME))));
	row("changes", vformat("surf %d  mat %d  shader %d", int(console_perf(Performance::RENDER_SURFACE_CHANGES_IN_FRAME)), int(console_perf(Performance::RENDER_MATERIAL_CHANGES_IN_FRAME)), int(console_perf(Performance::RENDER_SHADER_CHANGES_IN_FRAME))));
	row("vram", vformat("%s  (tex %s, vtx %s)", String::humanize_size((uint64_t)console_perf(Performance::RENDER_VIDEO_MEM_USED)), String::humanize_size((uint64_t)console_perf(Performance::RENDER_TEXTURE_MEM_USED)), String::humanize_size((uint64_t)console_perf(Performance::RENDER_VERTEX_MEM_USED))));

	// --- objects & memory -----------------------------------------------------------
	const int orphans = int(console_perf(Performance::OBJECT_ORPHAN_NODE_COUNT));
	row("objects", vformat("%d  nodes %d  res %d", ObjectDB::get_object_count(), int(console_perf(Performance::OBJECT_NODE_COUNT)), int(console_perf(Performance::OBJECT_RESOURCE_COUNT))));
	// Orphans are nodes that were never freed after being removed from the tree: the
	// cheapest leak canary a running game has.
	row("orphans", itos(orphans), orphans > 0 ? TextConsole::COLOR_YELLOW : TextConsole::COLOR_DARKGRAY);
	row("mem", vformat("%s static (peak %s)", String::humanize_size(os->get_static_memory_usage()), String::humanize_size(os->get_static_memory_peak_usage())));
	row("dynamic", vformat("%s (peak %s)", String::humanize_size((uint64_t)console_perf(Performance::MEMORY_DYNAMIC)), String::humanize_size((uint64_t)console_perf(Performance::MEMORY_DYNAMIC_MAX))));

	uint64_t sys_avail = 0, sys_total = 0;
	console_system_memory(sys_avail, sys_total);
	if (sys_total) {
		row("sysmem", vformat("%s free of %s", String::humanize_size(sys_avail), String::humanize_size(sys_total)),
				sys_avail < (sys_total / 10) ? TextConsole::COLOR_LIGHTRED : TextConsole::COLOR_DEFAULT);
	}
	if (sys_total) {
		const real_t used = real_t(sys_total - sys_avail) / real_t(sys_total);
		row("", meter(used, MAX(8, MIN(width - 12, 24))),
				used > 0.9 ? TextConsole::COLOR_LIGHTRED : TextConsole::COLOR_CYAN);
	}
	if (const uint64_t storage = console_storage_free()) {
		row("storage", String::humanize_size(storage) + " free");
	}

	const double latency = console_perf(Performance::AUDIO_OUTPUT_LATENCY);
	if (latency > 0) {
		row("audio", vformat("%.1f ms latency", latency * 1000.0));
	}
	row("watches", itos(watches.size()), TextConsole::COLOR_DARKGRAY);
}

void ConsoleInstance::_render_props() {
	if (watches.empty()) {
		console->logl(" no watches -- DebugConsole.add_var(name, object, property)", TextConsole::COLOR_DARKGRAY);
		return;
	}

	int name_width = 4;
	for (int i = 0; i < watches.size(); ++i) {
		name_width = MAX(name_width, String(watches[i].name).length());
	}
	name_width = MIN(name_width, MAX(4, console->get_console_size().width / 3));

	for (int i = 0; i < watches.size(); ++i) {
		const Watch &w = watches[i];
		String name = String(w.name);
		if (name.length() > name_width) {
			name = name.substr(0, name_width);
		}
		while (name.length() < name_width) {
			name += " ";
		}
		console->logl(" " + name + " " BOX_SUD " " + _format_value(w.cached), w.color);
	}
}

void ConsoleInstance::_render() {
	if (!console.is_valid()) {
		return;
	}

	console->clear();
	_render_header();
	switch (page) {
		case PAGE_LOG: {
			_render_log();
		} break;
		case PAGE_SYSINFO: {
			_render_sysinfo();
		} break;
		case PAGE_PROPS: {
			_render_props();
		} break;
		default: {
		}
	}
	dirty = false;
	update();
}

void ConsoleInstance::switch_page(Page p_page) {
	ERR_FAIL_INDEX(p_page, PAGE_MAX);
	page = p_page;
	if (page != PAGE_LOG) {
		_poll_watches();
	}
	_render();
}

ConsoleInstance::Page ConsoleInstance::get_page() const {
	return page;
}

void ConsoleInstance::next_page() {
	switch_page(Page((page + 1) % PAGE_MAX));
}

void ConsoleInstance::set_panel_touch_enabled(bool p_enabled) {
	panel_touch = p_enabled;
}

bool ConsoleInstance::is_panel_touch_enabled() const {
	return panel_touch;
}

void ConsoleInstance::prev_page() {
	switch_page(Page((page + PAGE_MAX - 1) % PAGE_MAX));
}

void ConsoleInstance::set_refresh_rate(real_t p_hz) {
	refresh_rate = CLAMP(p_hz, 0.1, 60.0);
}

real_t ConsoleInstance::get_refresh_rate() const {
	return refresh_rate;
}

void ConsoleInstance::log(const String &p_msg) {
	console_msg(p_msg);
}

void ConsoleInstance::log_colored(const String &p_msg, TextConsole::ColorIndex p_fg, TextConsole::ColorIndex p_bg) {
	_push_line(p_msg, p_fg, p_bg);
	if (page == PAGE_LOG) {
		_render();
	}
}

void ConsoleInstance::log_figlet(TextConsole::FigFontFace p_face, const String &p_msg, TextConsole::ColorIndex p_fg) {
	ERR_FAIL_COND(!console.is_valid());
	ERR_FAIL_INDEX(p_face, TextConsole::FigFontFaceCount);

	// Rendered off-grid so the banner text ends up in the ring buffer like everything else
	// and survives a reflow or a page switch.
	Ref<TextConsole> scratch = newref(TextConsole);
	scratch->load_font(console->get_font());
	scratch->resize(console->get_console_size().width, MAX(8, console->get_console_size().height));
	scratch->logf(p_face, p_msg, p_fg);

	const Size2i size = scratch->get_console_size();
	for (int y = 0; y < scratch->get_cursor().y; ++y) {
		String line;
		bool bank1 = false;
		for (int x = 0; x < size.width; ++x) {
			const TextConsole::cell &c = scratch->_screen[y * size.width + x];
			// Re-emit the bank toggle so the patched connector glyphs survive the round trip
			// through the ring buffer instead of falling back to the CP437 shape.
			if (bool(c.bank) != bank1) {
				line += String::chr(0x01);
				bank1 = !bank1;
			}
			line += String::chr(c.character ? uint8_t(c.character) : ' ');
		}
		if (bank1) {
			line += String::chr(0x01);
		}
		_push_raw_line(line.rstrip(" "), p_fg, TextConsole::COLOR_DEFAULT);
	}
	if (page == PAGE_LOG) {
		_render();
	}
}

void ConsoleInstance::clear_log() {
	{
		MutexLock lock(log_mutex);
		log_lines.clear();
	}
	dirty = true;
	if (page == PAGE_LOG) {
		_render();
	}
}

Size2i ConsoleInstance::lcd_size(const String &p_text) const {
	return console_lcd_size(p_text);
}

void ConsoleInstance::lcd_draw(int p_x, int p_y, const String &p_text, TextConsole::ColorIndex p_lit, TextConsole::ColorIndex p_dim) {
	if (console.is_null()) {
		return;
	}
	console_lcd_draw(*console.ptr(), p_x, p_y, p_text, p_lit, p_dim);
	update(); // show the poke immediately; the next page render will overwrite it
}

String ConsoleInstance::meter(real_t p_fraction, int p_cells) const {
	return console_meter(p_fraction, p_cells);
}

String ConsoleInstance::graph(const Vector<real_t> &p_values, int p_cells, real_t p_min, real_t p_max) const {
	return console_graph(p_values, p_cells, p_min, p_max);
}

void ConsoleInstance::set_value(const StringName &p_name, const Variant &p_value) {
	const int idx = _find_watch(p_name);
	if (idx >= 0) {
		watches.write[idx].cached = p_value;
	} else {
		Watch w;
		w.name = p_name;
		w.obj = 0;
		w.cached = p_value;
		w.color = TextConsole::COLOR_DEFAULT;
		watches.push_back(w);
	}
	dirty = true;
}

void ConsoleInstance::add_value(const StringName &p_name, const Ref<FuncRef> &p_getter) {
	ERR_FAIL_COND(p_getter.is_null());

	remove_watch(p_name);
	Watch w;
	w.name = p_name;
	w.obj = 0;
	w.getter = p_getter;
	w.color = TextConsole::COLOR_DEFAULT;
	watches.push_back(w);
	dirty = true;
}

void ConsoleInstance::add_var(const StringName &p_name, Object *p_object, const StringName &p_property) {
	ERR_FAIL_NULL(p_object);

	remove_watch(p_name);
	Watch w;
	w.name = p_name;
	w.obj = p_object->get_instance_id();
	w.property = p_property;
	w.color = TextConsole::COLOR_DEFAULT;
	watches.push_back(w);
	dirty = true;
}

void ConsoleInstance::remove_watch(const StringName &p_name) {
	const int idx = _find_watch(p_name);
	if (idx >= 0) {
		watches.remove(idx);
		dirty = true;
	}
}

void ConsoleInstance::clear_watches() {
	watches.clear();
	dirty = true;
}

Array ConsoleInstance::get_watch_names() const {
	Array names;
	for (int i = 0; i < watches.size(); ++i) {
		names.push_back(String(watches[i].name));
	}
	return names;
}

Ref<TextConsole> ConsoleInstance::get_console() const {
	return console;
}

void ConsoleInstance::_bind_methods() {
	ClassDB::bind_method(D_METHOD("_viewport_size_changed"), &ConsoleInstance::_viewport_size_changed);
	ClassDB::bind_method(D_METHOD("get_console"), &ConsoleInstance::get_console);
	ClassDB::bind_method(D_METHOD("set_font", "font"), &ConsoleInstance::set_font);
	ClassDB::bind_method(D_METHOD("get_font"), &ConsoleInstance::get_font);
	ClassDB::bind_method(D_METHOD("next_font"), &ConsoleInstance::next_font);
	ClassDB::bind_method(D_METHOD("set_pixel_scale", "scale"), &ConsoleInstance::set_pixel_scale);
	ClassDB::bind_method(D_METHOD("get_pixel_scale"), &ConsoleInstance::get_pixel_scale);
	ClassDB::bind_method(D_METHOD("set_auto_font", "enabled"), &ConsoleInstance::set_auto_font);
	ClassDB::bind_method(D_METHOD("is_auto_font"), &ConsoleInstance::is_auto_font);

	ClassDB::bind_method(D_METHOD("switch_page", "page"), &ConsoleInstance::switch_page);
	ClassDB::bind_method(D_METHOD("get_page"), &ConsoleInstance::get_page);
	ClassDB::bind_method(D_METHOD("next_page"), &ConsoleInstance::next_page);
	ClassDB::bind_method(D_METHOD("prev_page"), &ConsoleInstance::prev_page);
	ClassDB::bind_method(D_METHOD("set_panel_touch_enabled", "enabled"), &ConsoleInstance::set_panel_touch_enabled);
	ClassDB::bind_method(D_METHOD("is_panel_touch_enabled"), &ConsoleInstance::is_panel_touch_enabled);
	ClassDB::bind_method(D_METHOD("set_refresh_rate", "hz"), &ConsoleInstance::set_refresh_rate);
	ClassDB::bind_method(D_METHOD("get_refresh_rate"), &ConsoleInstance::get_refresh_rate);
	ClassDB::bind_method(D_METHOD("get_watch_names"), &ConsoleInstance::get_watch_names);

	BIND_ENUM_CONSTANT(PAGE_LOG);
	BIND_ENUM_CONSTANT(PAGE_SYSINFO);
	BIND_ENUM_CONSTANT(PAGE_PROPS);

	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_8x16, "DOS_8x16");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_8x12, "DOS_8x12");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_8x8, "DOS_8x8");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_7x9, "DOS_7x9");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_4x6, "DOS_4x6");

	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_BLACK, "COLOR_BLACK");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_BLUE, "COLOR_BLUE");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_GREEN, "COLOR_GREEN");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_RED, "COLOR_RED");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_MAGENTA, "COLOR_MAGENTA");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_BROWN, "COLOR_BROWN");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_LIGHTGRAY, "COLOR_LIGHTGRAY");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_LIGHTBLUE, "COLOR_LIGHTBLUE");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_LIGHTGREEN, "COLOR_LIGHTGREEN");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_LIGHTCYAN, "COLOR_LIGHTCYAN");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_LIGHTRED, "COLOR_LIGHTRED");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_LIGHTMAGENTA, "COLOR_LIGHTMAGENTA");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_WHITE, "COLOR_WHITE");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_TRANSPARENT, "COLOR_TRANSPARENT");

	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_FUTURE, "FUTURE");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_CALVIN_S, "CALVIN_S");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_ANSI_REGULAR, "ANSI_REGULAR");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_ANSI_SHADOW, "ANSI_SHADOW");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_DOS_REBEL, "DOS_REBEL");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_MAXIWI, "MAXIWI");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_MINIWI, "MINIWI");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_MAXII, "MAXII");
}

ConsoleInstance::ConsoleInstance() {
	console = Ref<TextConsole>(NULL);
	font_face = TextConsole::DOS_8x12;
	pixel_scale = 1;
	auto_font = true;
	page = PAGE_LOG;
	log_capacity = 1024;
	refresh_rate = 5.0;
	refresh_accum = 0;
	dirty = true;
	secondary_active = false;
	secondary_mode = _secondary_mode_setting();
	touch_down = false;
	touch_down_msec = 0;
	panel_touch = GLOBAL_DEF("debug/console/panel_touch", false);
}

ConsoleInstance::~ConsoleInstance() {
	{
		MutexLock lock(active_mutex);
		if (active == this) {
			active = nullptr;
		}
	}
}

DebugConsole *DebugConsole::singleton = nullptr;

DebugConsole::DebugConsole() {
	ERR_FAIL_COND(singleton != nullptr);
	singleton = this;
}

DebugConsole::~DebugConsole() {
	if (singleton == this) {
		singleton = nullptr;
	}
}

ConsoleInstance *DebugConsole::_instance(bool p_create) const {
	ConsoleInstance *inst = ConsoleInstance::get_active();
	if (!inst && p_create && SceneTree::get_singleton()) {
		// console_show() creates the node on demand and honours the release-build gate.
		SceneTree::get_singleton()->console_show(true);
		inst = ConsoleInstance::get_active();
	}
	return inst;
}

void DebugConsole::show(bool p_visible) {
	if (SceneTree::get_singleton()) {
		SceneTree::get_singleton()->console_show(p_visible);
	}
}

bool DebugConsole::is_visible() const {
	return SceneTree::get_singleton() ? SceneTree::get_singleton()->is_console_visible() : false;
}

#define _FORWARD(m_call, m_default)          \
	ConsoleInstance *inst = _instance(true); \
	if (!inst) {                             \
		return m_default;                    \
	}                                        \
	return inst->m_call;

#define _FORWARD_VOID(m_call)                      \
	if (ConsoleInstance *inst = _instance(true)) { \
		inst->m_call;                              \
	}

void DebugConsole::switch_page(int p_page) {
	ERR_FAIL_INDEX(p_page, ConsoleInstance::PAGE_MAX);
	_FORWARD_VOID(switch_page(ConsoleInstance::Page(p_page)));
}

void DebugConsole::set_panel_touch_enabled(bool p_enabled) {
	_FORWARD_VOID(set_panel_touch_enabled(p_enabled));
}

bool DebugConsole::is_panel_touch_enabled() const {
	_FORWARD(is_panel_touch_enabled(), false);
}

void DebugConsole::prev_page() {
	_FORWARD_VOID(prev_page());
}

void DebugConsole::next_page() {
	_FORWARD_VOID(next_page());
}

int DebugConsole::get_page() const {
	_FORWARD(get_page(), ConsoleInstance::PAGE_LOG);
}

void DebugConsole::set_font(int p_font) {
	ERR_FAIL_INDEX(p_font, TextConsole::DosFontCount);
	_FORWARD_VOID(set_font(TextConsole::FontSize(p_font)));
}

int DebugConsole::get_font() const {
	_FORWARD(get_font(), TextConsole::DOS_8x12);
}

void DebugConsole::next_font() {
	_FORWARD_VOID(next_font());
}

void DebugConsole::set_pixel_scale(int p_scale) {
	_FORWARD_VOID(set_pixel_scale(p_scale));
}

int DebugConsole::get_pixel_scale() const {
	_FORWARD(get_pixel_scale(), 1);
}

void DebugConsole::set_auto_font(bool p_enabled) {
	_FORWARD_VOID(set_auto_font(p_enabled));
}

bool DebugConsole::is_auto_font() const {
	_FORWARD(is_auto_font(), true);
}

void DebugConsole::set_refresh_rate(real_t p_hz) {
	_FORWARD_VOID(set_refresh_rate(p_hz));
}

real_t DebugConsole::get_refresh_rate() const {
	_FORWARD(get_refresh_rate(), 5.0);
}

void DebugConsole::log(const String &p_msg) {
	_FORWARD_VOID(log(p_msg));
}

void DebugConsole::log_colored(const String &p_msg, int p_fg, int p_bg) {
	ERR_FAIL_INDEX(p_fg, TextConsole::COLOR_COUNT + 1);
	ERR_FAIL_INDEX(p_bg, TextConsole::COLOR_COUNT + 1);
	_FORWARD_VOID(log_colored(p_msg, TextConsole::ColorIndex(p_fg), TextConsole::ColorIndex(p_bg)));
}

void DebugConsole::logf(int p_face, const String &p_msg) {
	ERR_FAIL_INDEX(p_face, TextConsole::FigFontFaceCount);
	_FORWARD_VOID(log_figlet(TextConsole::FigFontFace(p_face), p_msg));
}

void DebugConsole::clear_log() {
	_FORWARD_VOID(clear_log());
}

Vector2 DebugConsole::lcd_size(const String &p_text) const {
	ConsoleInstance *inst = _instance(true);
	if (!inst) {
		return Vector2();
	}
	const Size2i s = inst->lcd_size(p_text);
	return Vector2(s.width, s.height);
}

void DebugConsole::lcd_draw(int p_x, int p_y, const String &p_text, int p_lit, int p_dim) {
	ERR_FAIL_INDEX(p_lit, TextConsole::COLOR_COUNT + 1);
	ERR_FAIL_INDEX(p_dim, TextConsole::COLOR_COUNT + 1);
	_FORWARD_VOID(lcd_draw(p_x, p_y, p_text, TextConsole::ColorIndex(p_lit), TextConsole::ColorIndex(p_dim)));
}

String DebugConsole::meter(real_t p_fraction, int p_cells) {
	return console_meter(p_fraction, p_cells);
}

String DebugConsole::graph(const PoolRealArray &p_values, int p_cells, real_t p_min, real_t p_max) {
	// The script-facing type is a pool array; the gauge works on a plain Vector so it stays
	// usable from engine code that has no pool array to hand.
	Vector<real_t> values;
	values.resize(p_values.size());
	PoolRealArray::Read read = p_values.read();
	for (int i = 0; i < p_values.size(); ++i) {
		values.write[i] = read[i];
	}
	return console_graph(values, p_cells, p_min, p_max);
}

void DebugConsole::set_value(const StringName &p_name, const Variant &p_value) {
	_FORWARD_VOID(set_value(p_name, p_value));
}

void DebugConsole::add_value(const StringName &p_name, const Ref<FuncRef> &p_getter) {
	_FORWARD_VOID(add_value(p_name, p_getter));
}

void DebugConsole::add_var(const StringName &p_name, Object *p_object, const StringName &p_property) {
	_FORWARD_VOID(add_var(p_name, p_object, p_property));
}

void DebugConsole::remove(const StringName &p_name) {
	_FORWARD_VOID(remove_watch(p_name));
}

void DebugConsole::clear() {
	_FORWARD_VOID(clear_watches());
}

#undef _FORWARD
#undef _FORWARD_VOID

void DebugConsole::_bind_methods() {
	ClassDB::bind_method(D_METHOD("show", "visible"), &DebugConsole::show);
	ClassDB::bind_method(D_METHOD("is_visible"), &DebugConsole::is_visible);

	ClassDB::bind_method(D_METHOD("switch_page", "page"), &DebugConsole::switch_page);
	ClassDB::bind_method(D_METHOD("next_page"), &DebugConsole::next_page);
	ClassDB::bind_method(D_METHOD("prev_page"), &DebugConsole::prev_page);
	ClassDB::bind_method(D_METHOD("set_panel_touch_enabled", "enabled"), &DebugConsole::set_panel_touch_enabled);
	ClassDB::bind_method(D_METHOD("is_panel_touch_enabled"), &DebugConsole::is_panel_touch_enabled);
	ClassDB::bind_method(D_METHOD("get_page"), &DebugConsole::get_page);

	ClassDB::bind_method(D_METHOD("set_font", "font"), &DebugConsole::set_font);
	ClassDB::bind_method(D_METHOD("get_font"), &DebugConsole::get_font);
	ClassDB::bind_method(D_METHOD("next_font"), &DebugConsole::next_font);
	ClassDB::bind_method(D_METHOD("set_pixel_scale", "scale"), &DebugConsole::set_pixel_scale);
	ClassDB::bind_method(D_METHOD("get_pixel_scale"), &DebugConsole::get_pixel_scale);
	ClassDB::bind_method(D_METHOD("set_auto_font", "enabled"), &DebugConsole::set_auto_font);
	ClassDB::bind_method(D_METHOD("is_auto_font"), &DebugConsole::is_auto_font);
	ClassDB::bind_method(D_METHOD("set_refresh_rate", "hz"), &DebugConsole::set_refresh_rate);
	ClassDB::bind_method(D_METHOD("get_refresh_rate"), &DebugConsole::get_refresh_rate);

	ClassDB::bind_method(D_METHOD("log", "message"), &DebugConsole::log);
	ClassDB::bind_method(D_METHOD("log_colored", "message", "foreground", "background"), &DebugConsole::log_colored, DEFVAL(TextConsole::COLOR_DEFAULT), DEFVAL(TextConsole::COLOR_DEFAULT));
	ClassDB::bind_method(D_METHOD("logf", "face", "message"), &DebugConsole::logf);
	ClassDB::bind_method(D_METHOD("clear_log"), &DebugConsole::clear_log);

	ClassDB::bind_method(D_METHOD("lcd_size", "text"), &DebugConsole::lcd_size);
	ClassDB::bind_method(D_METHOD("lcd_draw", "x", "y", "text", "lit", "dim"), &DebugConsole::lcd_draw);
	ClassDB::bind_method(D_METHOD("meter", "fraction", "cells"), &DebugConsole::meter);
	ClassDB::bind_method(D_METHOD("graph", "values", "cells", "min", "max"),
			&DebugConsole::graph, DEFVAL(0.0), DEFVAL(0.0));

	ClassDB::bind_method(D_METHOD("set_value", "name", "value"), &DebugConsole::set_value);
	ClassDB::bind_method(D_METHOD("add_value", "name", "getter"), &DebugConsole::add_value);
	ClassDB::bind_method(D_METHOD("add_var", "name", "object", "property"), &DebugConsole::add_var);
	ClassDB::bind_method(D_METHOD("remove", "name"), &DebugConsole::remove);
	ClassDB::bind_method(D_METHOD("clear"), &DebugConsole::clear);

	BIND_ENUM_CONSTANT_CUSTOM(ConsoleInstance::PAGE_LOG, "PAGE_LOG");
	BIND_ENUM_CONSTANT_CUSTOM(ConsoleInstance::PAGE_SYSINFO, "PAGE_SYSINFO");
	BIND_ENUM_CONSTANT_CUSTOM(ConsoleInstance::PAGE_PROPS, "PAGE_PROPS");

	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_8x16, "DOS_8x16");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_8x12, "DOS_8x12");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_8x8, "DOS_8x8");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_7x9, "DOS_7x9");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::DOS_4x6, "DOS_4x6");

	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_FUTURE, "FIG_FUTURE");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_CALVIN_S, "FIG_CALVIN_S");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_ANSI_REGULAR, "FIG_ANSI_REGULAR");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_ANSI_SHADOW, "FIG_ANSI_SHADOW");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_DOS_REBEL, "FIG_DOS_REBEL");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_MAXIWI, "FIG_MAXIWI");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_MINIWI, "FIG_MINIWI");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::FIG_MAXII, "FIG_MAXII");

	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_BLACK, "COLOR_BLACK");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_WHITE, "COLOR_WHITE");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_RED, "COLOR_RED");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_GREEN, "COLOR_GREEN");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_YELLOW, "COLOR_YELLOW");
	BIND_ENUM_CONSTANT_CUSTOM(TextConsole::COLOR_DEFAULT, "COLOR_DEFAULT");
}

#ifdef DOCTEST

namespace {

String console_markup_plain(const String &p_text) {
	Vector<ConsoleMarkupRun> runs;
	console_parse_markup(p_text, runs);
	String out;
	for (int i = 0; i < runs.size(); ++i) {
		out += runs[i].text;
	}
	return out;
}

TextConsole::ColorIndex console_markup_fg_at(const String &p_text, int p_run) {
	Vector<ConsoleMarkupRun> runs;
	console_parse_markup(p_text, runs);
	REQUIRE(p_run < runs.size());
	return runs[p_run].foreground;
}

} // namespace

// Cells a console string occupies on the grid; the tail of console_measure() that the
// wrapper does not need, but which makes the intent testable.
static int console_cells(const String &p_text) {
	bool bank = false;
	int cells = 0;
	console_measure(p_text, 1 << 24, bank, cells);
	return cells;
}

/* The figlet faces smush with quarter-block shapes that CP437 has no codes for, so five
 * slots in the hand-edited atlases carry them instead of their stock glyphs (see the
 * mapping table at the bottom of figlet_font_miniwi.cpp). Nothing in the build checks that
 * the hand editing was actually done -- 0x0b was missed in all five faces and shipped as
 * the CP437 male sign, which showed up as a stray symbol in the middle of a figlet banner.
 *
 * The five shapes are not independent: each half block is the union of its two quadrants,
 * and the two diagonals are complements. Those identities pin every one of them down, so a
 * missed or mis-drawn edit cannot pass.
 */
namespace {

// One glyph as "#"/"." rows joined by "/", which compares directly and prints readably
// when an assertion fails.
String console_glyph_bits(const EmbedImageItem &p_face, int p_code) {
	const int cols = 16; // the raster is 16 glyphs across
	const int gx = p_code % cols, gy = p_code / cols;
	const int stride = cols * p_face.char_w;
	String out;
	for (int y = 0; y < p_face.char_h; ++y) {
		for (int x = 0; x < p_face.char_w; ++x) {
			out += p_face.pixels[(gy * p_face.char_h + y) * stride + gx * p_face.char_w + x] ? "#" : ".";
		}
		out += "/";
	}
	return out;
}

String console_glyph_or(const String &p_a, const String &p_b) {
	String out;
	for (int i = 0; i < p_a.length(); ++i) {
		out += (p_a[i] == '#' || p_b[i] == '#') ? "#" : String::chr(p_a[i]);
	}
	return out;
}

String console_glyph_not(const String &p_a) {
	String out;
	for (int i = 0; i < p_a.length(); ++i) {
		out += p_a[i] == '#' ? "." : (p_a[i] == '.' ? "#" : String::chr(p_a[i]));
	}
	return out;
}

} // namespace

/* logf() spells a bank 1 glyph with the \x01 toggle, and the toggle is sticky. Emitting a
 * closing toggle after every bank 1 glyph made the closing one and the opening one of an
 * adjacent bank 1 glyph collide into \x01\x01, which _put() reads as code 1 of bank 1: the
 * banner grew a stray cell and the bank stayed latched, so the half blocks after it came
 * out inverted. Adjacent bank 1 glyphs are the common case in the miniwi quadrants.
 */
namespace {

// Re-read a resolved line with the grammar of _put(), as "<code>/<bank>" per cell.
String console_decode_cells(const std::string &p_resolved) {
	String out;
	bool bank1 = false;
	for (size_t i = 0; i < p_resolved.size(); ++i) {
		bool cell_bank1 = bank1;
		unsigned char code = (unsigned char)p_resolved[i];
		if (code == 0x01) {
			if (i + 1 >= p_resolved.size()) {
				break; // dangling escape, nothing to draw
			}
			if ((unsigned char)p_resolved[i + 1] == 0x01) {
				++i;
				cell_bank1 = true;
			} else {
				bank1 = !bank1;
				continue;
			}
		}
		out += vformat("%d/%d ", int(code), int(cell_bank1));
	}
	return out;
}

} // namespace

/* Every hand-drawn bank 1 patch is authored lit-positive in the drawn (lower) half of the
 * atlas: a set pixel is a lit pixel, the same way make_vbars.py and make_sparkline.py
 * print the sheets they generate. A bank 1 patch is drawn as it stands -- unlike a bank 1
 * code without one, which is the bank 0 glyph with its colours swapped -- so a cell
 * authored in the black-on-white reading form comes out as a solid block with a hole in
 * it. The heavy connector strokes shipped that way and showed up as inverted cells in the
 * figlet faces that smush with them.
 *
 * Ink coverage tells the two apart without pinning down the artwork: a stroke or a gauge
 * level covers part of the cell, its negative covers nearly all of it.
 */
/* The hand-drawn bank 1 glyphs are authored in the atlas the way the rest of the sheet
 * reads -- black on white -- so make_fonts.py un-reverses them exactly as it un-reverses
 * the reference half. Getting that polarity wrong is invisible in the generated header
 * and only shows up on screen as solid blocks with a hole where the glyph should be, so
 * the gauge ladders are checked here: they are monotonic by construction, and a flip
 * turns each of them upside down while leaving every glyph the right size.
 */
TEST_CASE("Console patch glyph polarity") {
	const int SPARKLINE = 0x80, VBAR = 0x87; // 7 ascending levels each, see make_*.py
	for (int i = 0; embed_debug_font[i].pixels; ++i) {
		const EmbedImageItem &face = embed_debug_font[i];
		CAPTURE(face.image);
		const int cell = face.char_w * face.char_h;

		int lit[256];
		bool present[256] = {};
		for (int n = 0; n < face.patch_count; ++n) {
			const int code = face.patch_codes[n];
			int set = 0;
			for (int px = 0; px < cell; ++px) {
				set += face.patch[n * cell + px] ? 1 : 0;
			}
			lit[code] = set;
			present[code] = true;
			// A blank cell is not a glyph. There is no matching upper bound: the top level
			// of a ladder fills the cell outright where it is too narrow to resolve seven.
			CAPTURE(code);
			CHECK(set > 0);
		}

		// The smallest step of the narrowest face is a single row or column, so levels can
		// repeat where the cell is too small to resolve seven of them, but never descend.
		for (int base = SPARKLINE; base <= VBAR; base += VBAR - SPARKLINE) {
			for (int level = 0; level < 6; ++level) {
				if (!present[base + level] || !present[base + level + 1]) {
					continue;
				}
				CAPTURE(base);
				CAPTURE(level);
				CHECK(lit[base + level] <= lit[base + level + 1]);
			}
			// End to end the ladder has to actually climb, which pins the direction down.
			if (present[base] && present[base + 6]) {
				CHECK(lit[base] < lit[base + 6]);
			}
		}
	}
}

TEST_CASE("Console figlet placeholder resolution") {
	// The miniwi mapping, which is the one that uses every quadrant.
	const char *placeholders = "\003\004\005\006\007\010\011\013\014\016\017\020\021\022";
	const char *glyphs = "\010\010\012\012\017\017\336\336\337\337\334\334\335\335";
	const char *bank1 = "\004\006\007\013\016\020\022";

	// Every placeholder is exactly one cell, and each resolves to its mapped glyph and bank.
	for (int i = 0; placeholders[i]; ++i) {
		const std::string one(1, placeholders[i]);
		const bool want_bank1 = strchr(bank1, placeholders[i]) != nullptr;
		const String want = vformat("%d/%d ", int((unsigned char)glyphs[i]), int(want_bank1));
		CHECK(console_decode_cells(console_resolve_placeholders(one, placeholders, glyphs, bank1)) == want);
	}

	// A run of adjacent bank 1 glyphs, which is where the colliding toggles used to bite:
	// \x04 \x06 \x07 -> 0x08, 0x0a, 0x0f, all from bank 1, and nothing else.
	CHECK(console_decode_cells(console_resolve_placeholders("\004\006\007", placeholders, glyphs, bank1)) ==
			"8/1 10/1 15/1 ");

	// Alternating banks: the row of "lo" in miniwi, right half / upper left+right+lower
	// right / left half -- the bank must come back down for the plain glyph.
	CHECK(console_decode_cells(console_resolve_placeholders("\022\016\021\016\021", placeholders, glyphs, bank1)) ==
			"221/1 223/1 221/0 223/1 221/0 ");

	// Text mixed with placeholders keeps its own cells in bank 0.
	CHECK(console_decode_cells(console_resolve_placeholders("a\004b", placeholders, glyphs, bank1)) ==
			"97/0 8/1 98/0 ");

	// Resolution never changes the width of a row, whatever the mix.
	const std::string row = "\022\016\021 \004\004\017\020a\007\010";
	CHECK(console_resolve_placeholders(row, placeholders, glyphs, bank1).size() >= row.size());
	CHECK(console_decode_cells(console_resolve_placeholders(row, placeholders, glyphs, bank1)).split(" ", false).size() ==
			int(row.size()));

	// A face without a mapping table is passed through untouched.
	CHECK(console_resolve_placeholders("plain", nullptr, nullptr, nullptr) == "plain");
}

TEST_CASE("Console figlet quadrant glyphs") {
	enum {
		UPPER_LEFT = 0xde,
		LOWER_RIGHT = 0xdf,
		UPPER_RIGHT = 0x08,
		LOWER_LEFT = 0x0a,
		DIAGONAL = 0x0f, // upper right + lower left; the other diagonal is its inverse
		LOWER_HALF = 0xdc,
		LEFT_HALF = 0xdd,
	};

	for (int i = 0; embed_debug_font[i].pixels; ++i) {
		const EmbedImageItem &face = embed_debug_font[i];
		CAPTURE(face.image);

		const String ul = console_glyph_bits(face, UPPER_LEFT);
		const String ur = console_glyph_bits(face, UPPER_RIGHT);
		const String ll = console_glyph_bits(face, LOWER_LEFT);
		const String lr = console_glyph_bits(face, LOWER_RIGHT);
		const String low = console_glyph_bits(face, LOWER_HALF);
		const String left = console_glyph_bits(face, LEFT_HALF);
		const String diagonal = console_glyph_bits(face, DIAGONAL);

		// The two CP437 half blocks are the only shapes here that were never hand-edited,
		// so they are what anchors the other five to the real pixel grid.
		REQUIRE(console_glyph_or(ul, ur) == console_glyph_not(low)); // upper half
		REQUIRE(console_glyph_or(ll, lr) == low);
		REQUIRE(console_glyph_or(ul, ll) == left);
		REQUIRE(console_glyph_or(ur, lr) == console_glyph_not(left)); // right half
		REQUIRE(console_glyph_or(ur, ll) == diagonal);
		// Bank 1 has no patch at this code, so the console draws the other diagonal by
		// inverting this one; that only works if the two really are complements.
		REQUIRE(console_glyph_or(ul, lr) == console_glyph_not(diagonal));
	}
}

TEST_CASE("Console display width") {
	const String T = String::chr(0x01); // bank toggle

	SUBCASE("plain text is one cell per character") {
		REQUIRE(console_cells("") == 0);
		REQUIRE(console_cells("hello") == 5);
	}
	SUBCASE("bank toggles occupy no cells") {
		REQUIRE(console_cells(T + "ab" + T) == 2);
		REQUIRE(console_cells(T + T) == 1); // escaped literal, not a toggle of a toggle
		REQUIRE(console_cells("a" + T + T + "b") == 3);
	}
	SUBCASE("a dangling escape draws nothing") {
		REQUIRE(console_cells("ab" + T) == 2);
		REQUIRE(console_cells(T) == 0);
	}
	SUBCASE("the cut honours cells, not characters") {
		bool bank = false;
		int cells = 0;
		// Four letters carried by six characters: cutting at 4 cells must take the whole
		// string, which is what a figlet row needs in order not to wrap at two thirds of
		// the width.
		const String text = T + "ab" + T + "cd";
		const int cut = console_measure(text, 4, bank, cells);
		REQUIRE(cells == 4);
		REQUIRE(cut == text.length());
		REQUIRE(bank == false); // balanced toggles leave the grid in bank 0
	}
	SUBCASE("an unbalanced cut reports the open bank") {
		bool bank = false;
		int cells = 0;
		const String text = T + "abcdef";
		const int cut = console_measure(text, 3, bank, cells);
		REQUIRE(cells == 3);
		REQUIRE(cut == 4); // the toggle plus three letters
		REQUIRE(bank == true); // the continuation row has to re-open it
	}
}

TEST_CASE("Console markup") {
	SUBCASE("plain text passes through") {
		REQUIRE(console_markup_plain("hello world") == "hello world");
		REQUIRE(console_markup_plain("") == "");
	}
	SUBCASE("colour tags are consumed") {
		REQUIRE(console_markup_plain("[fg=red]hot[/fg]") == "hot");
		REQUIRE(console_markup_fg_at("[fg=red]hot[/fg]", 0) == TextConsole::COLOR_RED);
		REQUIRE(console_markup_plain("a[bg=blue]b[/bg]c") == "abc");
		REQUIRE(console_markup_fg_at("plain", 0) == TextConsole::COLOR_DEFAULT);
	}
	SUBCASE("colour is restored after a close tag") {
		Vector<ConsoleMarkupRun> runs;
		console_parse_markup("[fg=red]hot[/fg]cold", runs);
		REQUIRE(runs.size() == 2);
		REQUIRE(runs[0].foreground == TextConsole::COLOR_RED);
		REQUIRE(runs[1].foreground == TextConsole::COLOR_DEFAULT);
	}
	// Every case below used to spin the parser forever, freezing the whole engine on a
	// single log line. Malformed markup is common (log prefixes, array dumps, user text),
	// so it must always degrade to verbatim output.
	SUBCASE("unknown tags never stall") {
		REQUIRE(console_markup_plain("[Leaderboard] ready") == "[Leaderboard] ready");
		REQUIRE(console_markup_plain("[color=lightgreen]x[/color]") == "[color=lightgreen]x[/color]");
		REQUIRE(console_markup_plain("[]") == "[]");
		REQUIRE(console_markup_plain("[0][1][2]") == "[0][1][2]");
		REQUIRE(console_markup_plain("a[WARN]b[ERR]c") == "a[WARN]b[ERR]c");
	}
	SUBCASE("malformed colour tags never stall") {
		REQUIRE(console_markup_plain("[fg=nosuchcolor]x") == "[fg=nosuchcolor]x");
		REQUIRE(console_markup_plain("[fg=]x") == "[fg=]x");
		REQUIRE(console_markup_plain("[bg=]") == "[bg=]");
	}
	SUBCASE("unmatched close tags never stall") {
		REQUIRE(console_markup_plain("[/fg]") == "[/fg]");
		REQUIRE(console_markup_plain("[fg=red]x[/bg]") == "x[/bg]");
		REQUIRE(console_markup_plain("[/]") == "[/]");
	}
	SUBCASE("unterminated brackets never stall") {
		REQUIRE(console_markup_plain("[fg=red") == "[fg=red");
		REQUIRE(console_markup_plain("[") == "[");
		REQUIRE(console_markup_plain("ok [unclosed") == "ok [unclosed");
		REQUIRE(console_markup_plain("]") == "]");
	}
}

#endif // DOCTEST
