/* Generated by modules/gdextensions/_tools/make_fonts.py -- do not edit.
   Declarations for the glyph data in dos_font_data_8.h.

   font_<w>x<h>              bank 0: a 16 x 16 glyph raster of the regular CP437
							 glyphs, one byte per pixel (0x00 or 0xff).
   font_<w>x<h>_patch        bank 1: FONT_<W>X<H>_PATCH_COUNT glyph blocks of
							 w * h bytes, in the order of the code table below.
   font_<w>x<h>_patch_codes  the CP437 code each patch block belongs to.

   Bank 1 codes without a patch are rendered by inverting the bank 0 glyph at
   draw time. A face with no hand-edited glyphs has a patch count of 0. */

#ifndef DOS_FONT_DATA_H
#define DOS_FONT_DATA_H

#define FONT_8X16_PATCH_COUNT 18 /* 0x01 0x02 0x16 0x17 0x80 0x81 0x82 0x83 0x84 0x85 0x86 0x87 0x88 0x89 0x8a 0x8b 0x8c 0x8d */
#define FONT_8X12_PATCH_COUNT 18 /* 0x01 0x02 0x16 0x17 0x80 0x81 0x82 0x83 0x84 0x85 0x86 0x87 0x88 0x89 0x8a 0x8b 0x8c 0x8d */
#define FONT_7X9_PATCH_COUNT 18 /* 0x01 0x02 0x16 0x17 0x80 0x81 0x82 0x83 0x84 0x85 0x86 0x87 0x88 0x89 0x8a 0x8b 0x8c 0x8d */
#define FONT_8X8_PATCH_COUNT 18 /* 0x01 0x02 0x16 0x17 0x80 0x81 0x82 0x83 0x84 0x85 0x86 0x87 0x88 0x89 0x8a 0x8b 0x8c 0x8d */
#define FONT_4X6_PATCH_COUNT 18 /* 0x01 0x02 0x16 0x17 0x80 0x81 0x82 0x83 0x84 0x85 0x86 0x87 0x88 0x89 0x8a 0x8b 0x8c 0x8d */

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char font_8x16[], font_8x16_patch[], font_8x16_patch_codes[]; /* 8x16 */
extern const unsigned char font_8x12[], font_8x12_patch[], font_8x12_patch_codes[]; /* 8x12 */
extern const unsigned char font_7x9[], font_7x9_patch[], font_7x9_patch_codes[]; /* 7x9 */
extern const unsigned char font_8x8[], font_8x8_patch[], font_8x8_patch_codes[]; /* 8x8 */
extern const unsigned char font_4x6[], font_4x6_patch[], font_4x6_patch_codes[]; /* 4x6 */

#ifdef __cplusplus
}
#endif

#endif // DOS_FONT_DATA_H
