#!/usr/bin/env python

Import("env")

if not env["production"]:
    env.add_source_files(env.scene_sources, "*.cpp")
    env.add_source_files(env.scene_sources, "*.c")
    env.Append(CPPDEFINES=["GD_INAPP_CONSOLE"])
