#!/usr/bin/env python

Import("env")

env.add_source_files(env.drivers_sources, "*.cpp")
env.add_source_files(env.drivers_sources, "*.mm")
env.add_source_files(env.drivers_sources, "MGL/*.c")
env.add_source_files(env.drivers_sources, "MGL/*.cpp")

env.Append(FRAMEWORKS=["Metal", "Foundation"])

SConscript("metal/SCsub")
SConscript("shaders/SCsub")
SConscript("tools/SCsub")
