#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import platform_osx_builders

files = [
    "crash_handler_osx.mm",
    "os_osx.mm",
    "godot_main_osx.mm",
    "dir_access_osx.mm",
    "joypad_osx.cpp",
    "power_osx.cpp",
    "key_mapping_macos.mm",
    "menu_bar_mgr_osx.mm",
]

prog = env.add_program("#bin/godot", files)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(platform_osx_builders.make_debug_osx))

try:
    env.XcodeProject("../../Godot.xcodeproj", products=prog)
except AttributeError:
    # No xcode tool builder
    pass
