#!/usr/bin/env python3

Import("env")
Import("env_goost")

if env["builtin_libpng"]:
    env_goost.Append(CPPPATH=["#thirdparty/libpng/"])
env_goost.add_source_files(env_goost.sources, "drivers/png/*.cpp")
env_goost.add_source_files(env_goost.sources, "*.cpp")
