#!/usr/bin/env python3
"""Generate C++ icon lookup tables from IconFontCppHeaders .h files.

Parses #define ICON_XX_NAME "value" lines and generates a .gen.h file
with static arrays for runtime name-based lookups.

All UTF-8 values and metadata are inlined to avoid #define conflicts
between headers that share the same prefix (FA4, FA5, FA6, FA7).
"""

import os
import re
import sys

# Font definitions: (enum_name, prefix, header_file, filename_define, min_define, max_define)
FONTS = [
    ("FA6",  "ICON_FA_",  "IconsFontAwesome6.h",        "FONT_ICON_FILE_NAME_FAS", "ICON_MIN_FA",  "ICON_MAX_FA"),
    ("FA6B", "ICON_FA_",  "IconsFontAwesome6Brands.h",  "FONT_ICON_FILE_NAME_FAB", "ICON_MIN_FAB", "ICON_MAX_FAB"),
    ("FA5",  "ICON_FA_",  "IconsFontAwesome5.h",        "FONT_ICON_FILE_NAME_FAS", "ICON_MIN_FA",  "ICON_MAX_FA"),
    ("FA5B", "ICON_FA_",  "IconsFontAwesome5Brands.h",  "FONT_ICON_FILE_NAME_FAB", "ICON_MIN_FAB", "ICON_MAX_FAB"),
    ("FA4",  "ICON_FA_",  "IconsFontAwesome4.h",        "FONT_ICON_FILE_NAME_FA",  "ICON_MIN_FA",  "ICON_MAX_FA"),
    ("FA7",  "ICON_FA_",  "IconsFontAwesome7.h",        "FONT_ICON_FILE_NAME_FAS", "ICON_MIN_FA",  "ICON_MAX_FA"),
    ("FA7B", "ICON_FA_",  "IconsFontAwesome7Brands.h",  "FONT_ICON_FILE_NAME_FAB", "ICON_MIN_FAB", "ICON_MAX_FAB"),
    ("KI",   "ICON_KI_",  "IconsKenney.h",              "FONT_ICON_FILE_NAME_KI",  "ICON_MIN_KI",  "ICON_MAX_KI"),
    ("FAD",  "ICON_FAD_", "IconsFontaudio.h",            "FONT_ICON_FILE_NAME_FAD", "ICON_MIN_FAD", "ICON_MAX_FAD"),
    ("MD",   "ICON_MD_",  "IconsMaterialDesign.h",       "FONT_ICON_FILE_NAME_MD",  "ICON_MIN_MD",  "ICON_MAX_MD"),
    ("MDI",  "ICON_MDI_", "IconsMaterialDesignIcons.h",  "FONT_ICON_FILE_NAME_MDI", "ICON_MIN_MDI", "ICON_MAX_MDI"),
    ("FK",   "ICON_FK_",  "IconsForkAwesome.h",          "FONT_ICON_FILE_NAME_FK",  "ICON_MIN_FK",  "ICON_MAX_FK"),
    ("CI",   "ICON_CI_",  "IconsCodicons.h",             "FONT_ICON_FILE_NAME_CI",  "ICON_MIN_CI",  "ICON_MAX_CI"),
    ("LC",   "ICON_LC_",  "IconsLucide.h",               "FONT_ICON_FILE_NAME_LC",  "ICON_MIN_LC",  "ICON_MAX_LC"),
    ("MS",   "ICON_MS_",  "IconsMaterialSymbols.h",      "FONT_ICON_FILE_NAME_MSO", "ICON_MIN_MS",  "ICON_MAX_MS"),
]

# Metadata define prefixes (parsed but not emitted as C defines)
META_PREFIXES = ["ICON_MIN_", "ICON_MAX_", "ICON_MAX_16_", "FONT_ICON_FILE_NAME_"]


def parse_header(filepath, icon_prefix):
    """Parse a .h file and extract icon name -> UTF-8 value pairs and metadata."""
    icons = []
    meta = {}
    seen = set()
    icon_pattern = re.compile(r'^#define\s+({}(\w+))\s+"([^"]*)"'.format(re.escape(icon_prefix)))
    meta_str_pattern = re.compile(r'^#define\s+(\w+)\s+"([^"]*)"')
    meta_int_pattern = re.compile(r'^#define\s+(\w+)\s+(0x[0-9A-Fa-f]+)')

    with open(filepath, "r") as f:
        for line in f:
            # Check for metadata defines
            if any(line.startswith("#define " + mp) for mp in META_PREFIXES):
                ms = meta_str_pattern.match(line)
                if ms:
                    meta[ms.group(1)] = ms.group(2)
                else:
                    mi = meta_int_pattern.match(line)
                    if mi:
                        meta[mi.group(1)] = mi.group(2)
                continue

            m = icon_pattern.match(line)
            if m:
                short_name = m.group(2)   # e.g. ADDRESS_BOOK
                utf8_value = m.group(3)   # e.g. \xef\x80\x80
                key = short_name.lower()
                if key not in seen:
                    seen.add(key)
                    icons.append((short_name.lower(), utf8_value))

    return icons, meta


def c_escape(s):
    """Escape a string for use in a C string literal.

    The values from the headers are already C-escaped (\\xef\\x80\\x80),
    so we just need to pass them through. But we must handle any raw
    characters that might appear (like digits 0-9 for FA's digit icons).
    """
    return s


def generate(thirdparty_dir, output_path):
    """Generate the .gen.h file with inlined values (no header includes)."""
    lines = []
    lines.append("// AUTO-GENERATED by gen_icon_tables.py - DO NOT EDIT")
    lines.append("// Icon lookup tables for GdSymbolFonts")
    lines.append("// All values are inlined to avoid #define conflicts between font versions")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")

    # No #include of upstream headers - all values are inlined

    lines.append("struct IconEntry { const char *name; const char *utf8; };")
    lines.append("")

    font_data = []  # (enum_name, count, filename, icon_min, icon_max)

    for enum_name, prefix, header, fn_define, min_define, max_define in FONTS:
        filepath = os.path.join(thirdparty_dir, header)
        if not os.path.exists(filepath):
            print("  Warning: {} not found, skipping".format(header))
            lines.append("static const IconEntry {}_icons[] = {{}};".format(enum_name.lower()))
            lines.append("static const int {}_icon_count = 0;".format(enum_name.lower()))
            lines.append("")
            font_data.append((enum_name, 0, "unknown.ttf", "0", "0"))
            continue

        icons, meta = parse_header(filepath, prefix)
        print("  {}: {} icons".format(header, len(icons)))

        # Extract metadata
        filename = meta.get(fn_define, "unknown.ttf")
        icon_min = meta.get(min_define, "0")
        icon_max = meta.get(max_define, "0")
        font_data.append((enum_name, len(icons), filename, icon_min, icon_max))

        # Emit icon array with inlined UTF-8 values
        lines.append("static const IconEntry {}_icons[] = {{".format(enum_name.lower()))
        for name, value in icons:
            lines.append('\t{{ "{}", "{}" }},'.format(name, c_escape(value)))
        lines.append("};")
        lines.append("static const int {}_icon_count = {};".format(enum_name.lower(), len(icons)))
        lines.append("")

    # FontIconTable struct
    lines.append("struct FontIconTable {")
    lines.append("\tconst IconEntry *icons;")
    lines.append("\tint count;")
    lines.append("};")
    lines.append("")
    lines.append("static const FontIconTable icon_tables[] = {")
    for enum_name, _, _, _, _ in font_data:
        lines.append("\t{{ {}_icons, {}_icon_count }},".format(enum_name.lower(), enum_name.lower()))
    lines.append("};")
    lines.append("")

    # FontMeta struct with per-font metadata
    lines.append("struct FontMeta {")
    lines.append("\tconst char *filename;")
    lines.append("\tint icon_min;")
    lines.append("\tint icon_max;")
    lines.append("};")
    lines.append("")
    lines.append("static const FontMeta font_meta[] = {")
    for enum_name, count, filename, icon_min, icon_max in font_data:
        lines.append('\t{{ "{}", {}, {} }}, // {}'.format(filename, icon_min, icon_max, enum_name))
    lines.append("};")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    total = sum(d[1] for d in font_data)
    print("Generated {} with {} fonts, {} total icons".format(output_path, len(FONTS), total))


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    thirdparty_dir = os.path.join(script_dir, "..", "..", "thirdparty", "IconFontCppHeaders")
    output_path = os.path.join(script_dir, "icon_tables.gen.h")
    generate(thirdparty_dir, output_path)
