#!/usr/bin/env python

Import("env")
Import("env_modules")

env_yaml = env_modules.Clone()
env_glue = env_modules.Clone()

env_yaml.Prepend(CPPPATH=["."])
env_yaml.Prepend(CPPPATH=["#thirdparty/yaml-cpp/include"])

if (env["platform"] == "android" and not env["android_rtti"]) or (
    env["platform"] == "iphone" and not env["ios_exceptions"]
):
    env_yaml.Append(CPPFLAGS=["-frtti", "-fexceptions"])

env_yaml.Append(CPPDEFINES=["YAML_CPP_STATIC_DEFINE"])

# Compile as a static library
lib = env_yaml.Library("gdyaml", Glob("#thirdparty/yaml-cpp/src/*.cpp"))
glue = env_glue.Library("gdyaml_glue", Glob("*.cpp"))

# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib, glue])
