#include "scene/2d/node_2d.h"

class SpinnerCanvas;

enum {
	SPINNER,
	SPINNERANG,
	SPINNERDOTS,
	SPINNERANGNOBG,
	SPINNERANG270,
	SPINNERANG270NOBG,
	SPINNERVDOTS,
	SPINNERBOUNCEBALL,
	SPINNERANGECLIPSE,
	SPINNERINGYANG,
	SPINNERBARCHARTSINE,
	SPINNERBOUNCEDOTS,
	SPINNERFADEDOTS,
	SPINNERSCALEDOTS,
	SPINNERMOVINGDOTS,
	SPINNERROTATEDOTS,
	SPINNERTWINANG,
	SPINNERCLOCK,
	SPINNERINGYANGR,
	SPINNERBARCHARTSINE2,
	SPINNERTWINANG180,
	SPINNERTWINANG360,
	SPINNERINCDOTS,
	SPINNERDOTSWOBG,
	SPINNERINCSCALEDOTS,
	SPINNERANG90BG,
	SPINNERANG90,
	SPINNERFADEBARS,
	SPINNERPULSARSEQ,
	SPINNERINGYANGR2,
	SPINNERBARCHARTRAINBOW,
	SPINNERBARSROTATEFADE,
	SPINNERFADESCALEBARS,
	SPINNERBARSSCALEMIDDLE,
	SPINNERANGTWIN1,
	SPINNERANGTWIN2,
	SPINNERANGTWIN3,
	SPINNERANGTWIN4,
	SPINNERTWINPULSAR,
	SPINNERANGTWIN5,
	SPINNERBLOCKS,
	SPINNERTWINBALL,
	SPINNERTWINBALL2,
	SPINNERTWINBALL3,
	SPINNERANGTRIPLE,
	SPINNERINCFULLDOTS,
	SPINNERGOOEYBALLS,
	SPINNERROTATEGOOEYBALLS2,
	SPINNERROTATEGOOEYBALLS3,
	SPINNERMOONLINE,
	SPINNERARCROTATION,
	SPINNERARCFADE,
	SPINNERFILLING,
	SPINNERTOPUP,
	SPINNERFADEPULSAR,
	SPINNERFADEPULSAR2,
	SPINNERPULSAR,
	SPINNERDOUBLEFADEPULSAR,
	SPINNERFILLEDARCFADE,
	SPINNERFILLEDARCFADE6,
	SPINNERFILLEDARCFADE8,
	SPINNERFILLEDARCCOLOR,
	SPINNERCIRCLEDROP,
	SPINNERSURROUNDEDINDICATOR,
	SPINNERTRIANGLESSELETOR,
	SPINNERFLOWINGFRADIENT,
	SPINNERROTATESEGMENTS,
	SPINNERROTATESEGMENTS2,
	SPINNERROTATESEGMENTS3,
	SPINNERLEMNISCATE,
	SPINNERROTATEGEAR,
	SPINNERROTATEDATOM,
	SPINNERATOM,
	SPINNERRAINBOWBALLS,
	SPINNERCAMERA,
	SPINNERARCPOLARFADE,
	SPINNERARCPOLARRADIUS,
};

class Spinner : public Node2D {
	GDCLASS(Spinner, Node2D);

	Ref<SpinnerCanvas> canvas;

	int spinner_variant;
	void draw_spinners(int p_spinner);

protected:
	static void _bind_methods();
	void _notification(int p_notification);

public:
	Spinner();
};
