#!/usr/bin/env python

Import("env")
Import("env_modules")

env_module = env_modules.Clone()
env_module.Append(CPPPATH=[".", "#thirdparty/libgenerator/inc"])

sources = Glob("*.cpp") + Glob("#thirdparty/libgenerator/src/*.cpp")

# Compile as a static library
lib = env_module.Library("gd_generator", sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
