#!/usr/bin/env python

Import("env")
Import("env_modules")

import os

is_gcc = "gcc" in os.path.basename(env["CC"])

env_module = env_modules.Clone()
env_module.Append(CPPPATH=[".", "#modules/gdextensions", "#thirdparty/libgenerator/inc"])

sources = Glob("*.cpp") + Glob("#thirdparty/libgenerator/src/*.cpp")

if is_gcc:
	env_module.Append(CPPFLAGS=["-Wno-nonnull", "-Wno-array-bounds"]) # silent false warnings

# Compile as a static library
lib = env_module.Library("gd_generator", sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
